// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: admin.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMergeHistory = `-- name: CreateMergeHistory :one
INSERT INTO merge_history (surviving_id, merged_id, canonical_table, merged_by_user_id, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, surviving_id, merged_id, canonical_table, merged_by_user_id, reason, created_at
`

type CreateMergeHistoryParams struct {
	SurvivingID    pgtype.UUID `json:"surviving_id"`
	MergedID       pgtype.UUID `json:"merged_id"`
	CanonicalTable string      `json:"canonical_table"`
	MergedByUserID pgtype.UUID `json:"merged_by_user_id"`
	Reason         pgtype.Text `json:"reason"`
}

func (q *Queries) CreateMergeHistory(ctx context.Context, arg CreateMergeHistoryParams) (MergeHistory, error) {
	row := q.db.QueryRow(ctx, createMergeHistory,
		arg.SurvivingID,
		arg.MergedID,
		arg.CanonicalTable,
		arg.MergedByUserID,
		arg.Reason,
	)
	var i MergeHistory
	err := row.Scan(
		&i.ID,
		&i.SurvivingID,
		&i.MergedID,
		&i.CanonicalTable,
		&i.MergedByUserID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAliasesForMerged = `-- name: DeleteAliasesForMerged :exec
DELETE FROM person_aliases WHERE person_id = $1
`

func (q *Queries) DeleteAliasesForMerged(ctx context.Context, personID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAliasesForMerged, personID)
	return err
}

const deleteIdentifiersForMerged = `-- name: DeleteIdentifiersForMerged :exec
DELETE FROM person_identifiers WHERE person_id = $1
`

func (q *Queries) DeleteIdentifiersForMerged(ctx context.Context, personID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdentifiersForMerged, personID)
	return err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM persons WHERE id = $1
`

// DeletePerson hard-deletes the canonical person row. CASCADE on
// person_id FKs (employments, emails, etc.) takes the rest. Used by
// both the merge flow (final step, removes the merged_id) and the
// GDPR-style admin delete endpoint.
func (q *Queries) DeletePerson(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePerson, id)
	return err
}

const deleteSocialProfilesForMerged = `-- name: DeleteSocialProfilesForMerged :exec
DELETE FROM social_profiles WHERE person_id = $1
`

func (q *Queries) DeleteSocialProfilesForMerged(ctx context.Context, personID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSocialProfilesForMerged, personID)
	return err
}

const deleteTenantLeadsForMerged = `-- name: DeleteTenantLeadsForMerged :exec
DELETE FROM tenant_leads WHERE person_id = $1
`

func (q *Queries) DeleteTenantLeadsForMerged(ctx context.Context, personID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenantLeadsForMerged, personID)
	return err
}

const getConflict = `-- name: GetConflict :one
SELECT id, canonical_table, canonical_id, new_source_record_id, status, created_at
FROM conflict_queue
WHERE id = $1
`

func (q *Queries) GetConflict(ctx context.Context, id pgtype.UUID) (ConflictQueue, error) {
	row := q.db.QueryRow(ctx, getConflict, id)
	var i ConflictQueue
	err := row.Scan(
		&i.ID,
		&i.CanonicalTable,
		&i.CanonicalID,
		&i.NewSourceRecordID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one

SELECT id, canonical_name, first_name, last_name, normalized_name, created_at, updated_at
FROM persons
WHERE id = $1
`

type GetPersonRow struct {
	ID             pgtype.UUID        `json:"id"`
	CanonicalName  string             `json:"canonical_name"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	NormalizedName string             `json:"normalized_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================================
// Person detail (a handful of focused queries — handler aggregates)
// ============================================================================
func (q *Queries) GetPerson(ctx context.Context, id pgtype.UUID) (GetPersonRow, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i GetPersonRow
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.FirstName,
		&i.LastName,
		&i.NormalizedName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConflicts = `-- name: ListConflicts :many


SELECT
    cq.id,
    cq.canonical_table,
    cq.canonical_id,
    cq.new_source_record_id,
    cq.status,
    cq.created_at,
    p.canonical_name AS person_canonical_name,
    sr.fields        AS source_record_fields,
    s.name           AS source_name
FROM conflict_queue cq
JOIN source_records sr ON sr.id = cq.new_source_record_id
JOIN sources s         ON s.id = sr.source_id
LEFT JOIN persons p ON cq.canonical_table = 'persons' AND p.id = cq.canonical_id
WHERE ($3::text IS NULL OR cq.status = $3::text)
ORDER BY cq.created_at DESC
LIMIT $1 OFFSET $2
`

type ListConflictsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status pgtype.Text `json:"status"`
}

type ListConflictsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	CanonicalTable      string             `json:"canonical_table"`
	CanonicalID         pgtype.UUID        `json:"canonical_id"`
	NewSourceRecordID   pgtype.UUID        `json:"new_source_record_id"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	PersonCanonicalName pgtype.Text        `json:"person_canonical_name"`
	SourceRecordFields  []byte             `json:"source_record_fields"`
	SourceName          string             `json:"source_name"`
}

// Admin panel queries — conflict review, person inspection, merge,
// and hard delete. Plan §T14.
//
// The merge endpoint runs a multi-statement transaction in the
// handler (see internal/handler/admin.go). Each reassignment query
// below is shaped so the handler can execute them in order under one
// pgx.Tx and have the FK-bearing rows re-pointed without violating
// the unique constraints in 015_alias_uniqueness.
// ============================================================================
// Conflict queue
// ============================================================================
// ListConflicts returns the conflict queue, newest first, with the
// linked canonical person's name and the source the new record came
// from. Filter by status with sqlc.narg('status') = NULL for "all".
func (q *Queries) ListConflicts(ctx context.Context, arg ListConflictsParams) ([]ListConflictsRow, error) {
	rows, err := q.db.Query(ctx, listConflicts, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConflictsRow{}
	for rows.Next() {
		var i ListConflictsRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalTable,
			&i.CanonicalID,
			&i.NewSourceRecordID,
			&i.Status,
			&i.CreatedAt,
			&i.PersonCanonicalName,
			&i.SourceRecordFields,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonAliases = `-- name: ListPersonAliases :many
SELECT id, alias, alias_type FROM person_aliases
WHERE person_id = $1
ORDER BY alias
`

type ListPersonAliasesRow struct {
	ID        pgtype.UUID `json:"id"`
	Alias     string      `json:"alias"`
	AliasType string      `json:"alias_type"`
}

func (q *Queries) ListPersonAliases(ctx context.Context, personID pgtype.UUID) ([]ListPersonAliasesRow, error) {
	rows, err := q.db.Query(ctx, listPersonAliases, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonAliasesRow{}
	for rows.Next() {
		var i ListPersonAliasesRow
		if err := rows.Scan(&i.ID, &i.Alias, &i.AliasType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonEmails = `-- name: ListPersonEmails :many
SELECT id, email, verified_at, verification_method, bounce_count, is_catchall, created_at
FROM emails
WHERE person_id = $1
ORDER BY (verified_at IS NOT NULL) DESC, bounce_count ASC, created_at ASC
`

type ListPersonEmailsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	VerificationMethod pgtype.Text        `json:"verification_method"`
	BounceCount        pgtype.Int4        `json:"bounce_count"`
	IsCatchall         pgtype.Bool        `json:"is_catchall"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPersonEmails(ctx context.Context, personID pgtype.UUID) ([]ListPersonEmailsRow, error) {
	rows, err := q.db.Query(ctx, listPersonEmails, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonEmailsRow{}
	for rows.Next() {
		var i ListPersonEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.VerifiedAt,
			&i.VerificationMethod,
			&i.BounceCount,
			&i.IsCatchall,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonEmployments = `-- name: ListPersonEmployments :many
SELECT
    e.id, e.title, e.start_date, e.end_date, e.is_current, e.created_at,
    o.id            AS organization_id,
    o.canonical_name AS organization_name,
    o.primary_domain
FROM employments e
JOIN organizations o ON o.id = e.organization_id
WHERE e.person_id = $1
ORDER BY e.is_current DESC, e.start_date DESC NULLS LAST
`

type ListPersonEmploymentsRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            pgtype.Text        `json:"title"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	IsCurrent        pgtype.Bool        `json:"is_current"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	OrganizationName string             `json:"organization_name"`
	PrimaryDomain    pgtype.Text        `json:"primary_domain"`
}

func (q *Queries) ListPersonEmployments(ctx context.Context, personID pgtype.UUID) ([]ListPersonEmploymentsRow, error) {
	rows, err := q.db.Query(ctx, listPersonEmployments, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonEmploymentsRow{}
	for rows.Next() {
		var i ListPersonEmploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrent,
			&i.CreatedAt,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.PrimaryDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonEvidence = `-- name: ListPersonEvidence :many
SELECT
    ev.id,
    ev.confidence,
    ev.conflict_flag,
    ev.created_at,
    ev.source_record_id,
    sr.external_id,
    sr.fields,
    sr.ingested_at,
    s.id   AS source_id,
    s.name AS source_name,
    s.type AS source_type
FROM evidence ev
JOIN source_records sr ON sr.id = ev.source_record_id
JOIN sources s         ON s.id = sr.source_id
WHERE ev.canonical_table = 'persons' AND ev.canonical_id = $1
ORDER BY ev.created_at DESC
`

type ListPersonEvidenceRow struct {
	ID             pgtype.UUID        `json:"id"`
	Confidence     int16              `json:"confidence"`
	ConflictFlag   pgtype.Bool        `json:"conflict_flag"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	SourceRecordID pgtype.UUID        `json:"source_record_id"`
	ExternalID     pgtype.Text        `json:"external_id"`
	Fields         []byte             `json:"fields"`
	IngestedAt     pgtype.Timestamptz `json:"ingested_at"`
	SourceID       pgtype.UUID        `json:"source_id"`
	SourceName     string             `json:"source_name"`
	SourceType     string             `json:"source_type"`
}

// ListPersonEvidence joins each evidence row to its source_record
// and the originating source so the admin can see "where did this
// claim come from?" without hitting raw_ingests directly.
func (q *Queries) ListPersonEvidence(ctx context.Context, canonicalID pgtype.UUID) ([]ListPersonEvidenceRow, error) {
	rows, err := q.db.Query(ctx, listPersonEvidence, canonicalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonEvidenceRow{}
	for rows.Next() {
		var i ListPersonEvidenceRow
		if err := rows.Scan(
			&i.ID,
			&i.Confidence,
			&i.ConflictFlag,
			&i.CreatedAt,
			&i.SourceRecordID,
			&i.ExternalID,
			&i.Fields,
			&i.IngestedAt,
			&i.SourceID,
			&i.SourceName,
			&i.SourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonIdentifiers = `-- name: ListPersonIdentifiers :many
SELECT id, identifier_type, identifier_value, is_primary FROM person_identifiers
WHERE person_id = $1
ORDER BY identifier_type, identifier_value
`

type ListPersonIdentifiersRow struct {
	ID              pgtype.UUID `json:"id"`
	IdentifierType  string      `json:"identifier_type"`
	IdentifierValue string      `json:"identifier_value"`
	IsPrimary       pgtype.Bool `json:"is_primary"`
}

func (q *Queries) ListPersonIdentifiers(ctx context.Context, personID pgtype.UUID) ([]ListPersonIdentifiersRow, error) {
	rows, err := q.db.Query(ctx, listPersonIdentifiers, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonIdentifiersRow{}
	for rows.Next() {
		var i ListPersonIdentifiersRow
		if err := rows.Scan(
			&i.ID,
			&i.IdentifierType,
			&i.IdentifierValue,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonPhones = `-- name: ListPersonPhones :many
SELECT id, phone, verified_at, created_at FROM phones
WHERE person_id = $1
ORDER BY created_at
`

type ListPersonPhonesRow struct {
	ID         pgtype.UUID        `json:"id"`
	Phone      string             `json:"phone"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPersonPhones(ctx context.Context, personID pgtype.UUID) ([]ListPersonPhonesRow, error) {
	rows, err := q.db.Query(ctx, listPersonPhones, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonPhonesRow{}
	for rows.Next() {
		var i ListPersonPhonesRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonSocialProfiles = `-- name: ListPersonSocialProfiles :many
SELECT id, platform, handle, url, created_at FROM social_profiles
WHERE person_id = $1
ORDER BY platform
`

type ListPersonSocialProfilesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Platform  string             `json:"platform"`
	Handle    pgtype.Text        `json:"handle"`
	Url       pgtype.Text        `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPersonSocialProfiles(ctx context.Context, personID pgtype.UUID) ([]ListPersonSocialProfilesRow, error) {
	rows, err := q.db.Query(ctx, listPersonSocialProfiles, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonSocialProfilesRow{}
	for rows.Next() {
		var i ListPersonSocialProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Handle,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAliasesForMerge = `-- name: MoveAliasesForMerge :exec

INSERT INTO person_aliases (person_id, alias, alias_type)
SELECT $1::uuid, alias, alias_type
FROM person_aliases
WHERE person_id = $2::uuid
ON CONFLICT ON CONSTRAINT person_aliases_unique DO NOTHING
`

type MoveAliasesForMergeParams struct {
	KeepID   pgtype.UUID `json:"keep_id"`
	MergedID pgtype.UUID `json:"merged_id"`
}

// ============================================================================
// Merge persons (run inside one pgx.Tx in the handler)
// ============================================================================
//
// Step order matters: aliases / identifiers / social_profiles /
// tenant_leads have unique constraints that the merged person may
// already satisfy, so we copy what doesn't conflict and then drop
// the originals before flipping the simpler FK tables.
func (q *Queries) MoveAliasesForMerge(ctx context.Context, arg MoveAliasesForMergeParams) error {
	_, err := q.db.Exec(ctx, moveAliasesForMerge, arg.KeepID, arg.MergedID)
	return err
}

const moveIdentifiersForMerge = `-- name: MoveIdentifiersForMerge :exec
UPDATE person_identifiers
SET person_id = $1::uuid
WHERE person_id = $2::uuid
  AND NOT EXISTS (
    SELECT 1 FROM person_identifiers ki
    WHERE ki.person_id = $1::uuid
      AND ki.identifier_value = person_identifiers.identifier_value
  )
`

type MoveIdentifiersForMergeParams struct {
	KeepID   pgtype.UUID `json:"keep_id"`
	MergedID pgtype.UUID `json:"merged_id"`
}

// person_identifiers.identifier_value is globally UNIQUE, so the
// insert-then-delete trick used for aliases would have ON CONFLICT
// skip the new row and then DELETE drop the original — losing the
// identifier. Repoint via UPDATE instead, only for values the
// survivor doesn't already have. Anything the survivor already
// carries is left to the DELETE.
func (q *Queries) MoveIdentifiersForMerge(ctx context.Context, arg MoveIdentifiersForMergeParams) error {
	_, err := q.db.Exec(ctx, moveIdentifiersForMerge, arg.KeepID, arg.MergedID)
	return err
}

const moveSocialProfilesForMerge = `-- name: MoveSocialProfilesForMerge :exec
UPDATE social_profiles
SET person_id = $1::uuid
WHERE person_id = $2::uuid
  AND NOT EXISTS (
    SELECT 1 FROM social_profiles ks
    WHERE ks.person_id = $1::uuid
      AND ks.platform = social_profiles.platform
      AND ks.url = social_profiles.url
  )
`

type MoveSocialProfilesForMergeParams struct {
	KeepID   pgtype.UUID `json:"keep_id"`
	MergedID pgtype.UUID `json:"merged_id"`
}

// social_profiles.(platform, url) is globally UNIQUE — same shape as
// identifiers, so use the same UPDATE-WHERE-NOT-EXISTS pattern.
func (q *Queries) MoveSocialProfilesForMerge(ctx context.Context, arg MoveSocialProfilesForMergeParams) error {
	_, err := q.db.Exec(ctx, moveSocialProfilesForMerge, arg.KeepID, arg.MergedID)
	return err
}

const moveTenantLeadsForMerge = `-- name: MoveTenantLeadsForMerge :exec
INSERT INTO tenant_leads (tenant_id, person_id, status, notes, added_at, added_by_user_id)
SELECT tenant_id, $1::uuid, status, notes, added_at, added_by_user_id
FROM tenant_leads
WHERE person_id = $2::uuid
ON CONFLICT (tenant_id, person_id) DO NOTHING
`

type MoveTenantLeadsForMergeParams struct {
	KeepID   pgtype.UUID `json:"keep_id"`
	MergedID pgtype.UUID `json:"merged_id"`
}

// tenant_leads: PRIMARY KEY (tenant_id, person_id) → re-point with
// ON CONFLICT to keep both saves merged into the surviving person.
func (q *Queries) MoveTenantLeadsForMerge(ctx context.Context, arg MoveTenantLeadsForMergeParams) error {
	_, err := q.db.Exec(ctx, moveTenantLeadsForMerge, arg.KeepID, arg.MergedID)
	return err
}

const reassignCampaignLeadsForMerge = `-- name: ReassignCampaignLeadsForMerge :exec

UPDATE campaign_leads
SET person_id = $1::uuid
WHERE person_id = $2::uuid
`

type ReassignCampaignLeadsForMergeParams struct {
	KeepID   pgtype.UUID `json:"keep_id"`
	MergedID pgtype.UUID `json:"merged_id"`
}

// The legacy `leads` and `campaign_leads` tables both carry a
// nullable person_id bridge column (migrations 013 and 016). Repoint
// them too so existing per-tenant lead histories survive a merge.
func (q *Queries) ReassignCampaignLeadsForMerge(ctx context.Context, arg ReassignCampaignLeadsForMergeParams) error {
	_, err := q.db.Exec(ctx, reassignCampaignLeadsForMerge, arg.KeepID, arg.MergedID)
	return err
}

const reassignEmailsForMerge = `-- name: ReassignEmailsForMerge :exec
UPDATE emails
SET person_id = $1::uuid
WHERE person_id = $2::uuid
`

type ReassignEmailsForMergeParams struct {
	KeepID   pgtype.UUID `json:"keep_id"`
	MergedID pgtype.UUID `json:"merged_id"`
}

func (q *Queries) ReassignEmailsForMerge(ctx context.Context, arg ReassignEmailsForMergeParams) error {
	_, err := q.db.Exec(ctx, reassignEmailsForMerge, arg.KeepID, arg.MergedID)
	return err
}

const reassignEmploymentsForMerge = `-- name: ReassignEmploymentsForMerge :exec
UPDATE employments
SET person_id = $1::uuid
WHERE person_id = $2::uuid
`

type ReassignEmploymentsForMergeParams struct {
	KeepID   pgtype.UUID `json:"keep_id"`
	MergedID pgtype.UUID `json:"merged_id"`
}

func (q *Queries) ReassignEmploymentsForMerge(ctx context.Context, arg ReassignEmploymentsForMergeParams) error {
	_, err := q.db.Exec(ctx, reassignEmploymentsForMerge, arg.KeepID, arg.MergedID)
	return err
}

const reassignEvidenceForMerge = `-- name: ReassignEvidenceForMerge :exec

UPDATE evidence
SET canonical_id = $1::uuid
WHERE canonical_table = 'persons'
  AND canonical_id = $2::uuid
`

type ReassignEvidenceForMergeParams struct {
	KeepID   pgtype.UUID `json:"keep_id"`
	MergedID pgtype.UUID `json:"merged_id"`
}

// evidence / employments / emails / phones have no in-table unique
// collisions on person_id, so a plain repoint suffices.
func (q *Queries) ReassignEvidenceForMerge(ctx context.Context, arg ReassignEvidenceForMergeParams) error {
	_, err := q.db.Exec(ctx, reassignEvidenceForMerge, arg.KeepID, arg.MergedID)
	return err
}

const reassignLegacyLeadsForMerge = `-- name: ReassignLegacyLeadsForMerge :exec
UPDATE leads
SET person_id = $1::uuid
WHERE person_id = $2::uuid
`

type ReassignLegacyLeadsForMergeParams struct {
	KeepID   pgtype.UUID `json:"keep_id"`
	MergedID pgtype.UUID `json:"merged_id"`
}

func (q *Queries) ReassignLegacyLeadsForMerge(ctx context.Context, arg ReassignLegacyLeadsForMergeParams) error {
	_, err := q.db.Exec(ctx, reassignLegacyLeadsForMerge, arg.KeepID, arg.MergedID)
	return err
}

const reassignPhonesForMerge = `-- name: ReassignPhonesForMerge :exec
UPDATE phones
SET person_id = $1::uuid
WHERE person_id = $2::uuid
`

type ReassignPhonesForMergeParams struct {
	KeepID   pgtype.UUID `json:"keep_id"`
	MergedID pgtype.UUID `json:"merged_id"`
}

func (q *Queries) ReassignPhonesForMerge(ctx context.Context, arg ReassignPhonesForMergeParams) error {
	_, err := q.db.Exec(ctx, reassignPhonesForMerge, arg.KeepID, arg.MergedID)
	return err
}

const updateConflictStatus = `-- name: UpdateConflictStatus :exec
UPDATE conflict_queue SET status = $2 WHERE id = $1
`

type UpdateConflictStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateConflictStatus(ctx context.Context, arg UpdateConflictStatusParams) error {
	_, err := q.db.Exec(ctx, updateConflictStatus, arg.ID, arg.Status)
	return err
}
