// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaign_leads.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateCampaignLeads = `-- name: ActivateCampaignLeads :exec
UPDATE campaign_leads SET status = 'active', next_send_at = NOW()
WHERE campaign_id = $1 AND status = 'queued'
`

func (q *Queries) ActivateCampaignLeads(ctx context.Context, campaignID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateCampaignLeads, campaignID)
	return err
}

const addLeadToCampaign = `-- name: AddLeadToCampaign :exec
INSERT INTO campaign_leads (campaign_id, lead_id, status)
VALUES ($1, $2, 'queued')
ON CONFLICT DO NOTHING
`

type AddLeadToCampaignParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	LeadID     pgtype.UUID `json:"lead_id"`
}

// Legacy: add a row via the lead_id path. Kept while the pipeline
// still runs; T07 deletes it.
func (q *Queries) AddLeadToCampaign(ctx context.Context, arg AddLeadToCampaignParams) error {
	_, err := q.db.Exec(ctx, addLeadToCampaign, arg.CampaignID, arg.LeadID)
	return err
}

const addPersonToCampaign = `-- name: AddPersonToCampaign :exec
INSERT INTO campaign_leads (campaign_id, person_id, status)
VALUES ($1, $2, 'queued')
ON CONFLICT DO NOTHING
`

type AddPersonToCampaignParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	PersonID   pgtype.UUID `json:"person_id"`
}

// New canonical path — add a saved person to a campaign.
func (q *Queries) AddPersonToCampaign(ctx context.Context, arg AddPersonToCampaignParams) error {
	_, err := q.db.Exec(ctx, addPersonToCampaign, arg.CampaignID, arg.PersonID)
	return err
}

const countCampaignLeadsByStatus = `-- name: CountCampaignLeadsByStatus :many
SELECT status, COUNT(*) as count FROM campaign_leads
WHERE campaign_id = $1
GROUP BY status
`

type CountCampaignLeadsByStatusRow struct {
	Status pgtype.Text `json:"status"`
	Count  int64       `json:"count"`
}

func (q *Queries) CountCampaignLeadsByStatus(ctx context.Context, campaignID pgtype.UUID) ([]CountCampaignLeadsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countCampaignLeadsByStatus, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCampaignLeadsByStatusRow{}
	for rows.Next() {
		var i CountCampaignLeadsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDueLeads = `-- name: GetDueLeads :many
WITH best AS (
    SELECT DISTINCT ON (em.person_id)
        em.person_id,
        em.email,
        em.verified_at,
        em.is_catchall,
        em.bounce_count
    FROM emails em
    ORDER BY em.person_id,
             (em.verified_at IS NOT NULL) DESC,
             em.bounce_count ASC,
             em.created_at ASC
), current_emp AS (
    SELECT DISTINCT ON (emp.person_id)
        emp.person_id,
        emp.title,
        emp.organization_id
    FROM employments emp
    WHERE emp.is_current = TRUE
    ORDER BY emp.person_id, emp.start_date DESC NULLS LAST
)
SELECT
    cl.id,
    cl.campaign_id,
    cl.lead_id,
    cl.person_id,
    cl.status,
    cl.current_step,
    cl.next_send_at,
    COALESCE(b.email, l.email, '')::text             AS email,
    COALESCE(p.first_name, l.first_name, '')::text   AS first_name,
    COALESCE(p.last_name,  l.last_name,  '')::text   AS last_name,
    COALESCE(o.canonical_name, l.company, '')::text  AS company,
    COALESCE(ce.title, l.title)                      AS title
FROM campaign_leads cl
LEFT JOIN leads         l  ON l.id  = cl.lead_id
LEFT JOIN persons       p  ON p.id  = cl.person_id
LEFT JOIN best          b  ON b.person_id = cl.person_id
LEFT JOIN current_emp   ce ON ce.person_id = cl.person_id
LEFT JOIN organizations o  ON o.id = ce.organization_id
WHERE cl.next_send_at <= NOW()
  AND cl.status = 'active'
ORDER BY cl.next_send_at
LIMIT $1
`

type GetDueLeadsRow struct {
	ID          pgtype.UUID        `json:"id"`
	CampaignID  pgtype.UUID        `json:"campaign_id"`
	LeadID      pgtype.UUID        `json:"lead_id"`
	PersonID    pgtype.UUID        `json:"person_id"`
	Status      pgtype.Text        `json:"status"`
	CurrentStep pgtype.Int4        `json:"current_step"`
	NextSendAt  pgtype.Timestamptz `json:"next_send_at"`
	Email       string             `json:"email"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Company     string             `json:"company"`
	Title       pgtype.Text        `json:"title"`
}

// GetDueLeads resolves the contact fields from either the canonical
// persons graph (when campaign_leads.person_id is set) or the legacy
// leads row (lead_id). The sender reads a unified row shape regardless
// of which path populated it.
//
// For the canonical path we pull the best email per person (verified
// wins, then fewest bounces, then oldest) and the current employment
// for title/company.
func (q *Queries) GetDueLeads(ctx context.Context, limit int32) ([]GetDueLeadsRow, error) {
	rows, err := q.db.Query(ctx, getDueLeads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDueLeadsRow{}
	for rows.Next() {
		var i GetDueLeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.LeadID,
			&i.PersonID,
			&i.Status,
			&i.CurrentStep,
			&i.NextSendAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Company,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignLeads = `-- name: ListCampaignLeads :many
WITH best AS (
    SELECT DISTINCT ON (em.person_id)
        em.person_id,
        em.email
    FROM emails em
    ORDER BY em.person_id,
             (em.verified_at IS NOT NULL) DESC,
             em.bounce_count ASC,
             em.created_at ASC
), current_emp AS (
    SELECT DISTINCT ON (emp.person_id)
        emp.person_id,
        emp.title,
        emp.organization_id
    FROM employments emp
    WHERE emp.is_current = TRUE
    ORDER BY emp.person_id, emp.start_date DESC NULLS LAST
)
SELECT
    cl.id,
    cl.campaign_id,
    cl.lead_id,
    cl.person_id,
    cl.status,
    cl.current_step,
    cl.next_send_at,
    cl.last_sent_at,
    cl.last_opened_at,
    cl.last_replied_at,
    cl.created_at,
    COALESCE(p.first_name,    l.first_name, '')::text   AS first_name,
    COALESCE(p.last_name,     l.last_name,  '')::text   AS last_name,
    COALESCE(b.email,         l.email,      '')::text   AS email,
    COALESCE(ce.title,        l.title)                  AS title,
    COALESCE(o.canonical_name, l.company,   '')::text   AS company,
    l.linkedin_url                                       AS linkedin_url
FROM campaign_leads cl
LEFT JOIN leads         l  ON l.id  = cl.lead_id
LEFT JOIN persons       p  ON p.id  = cl.person_id
LEFT JOIN best          b  ON b.person_id = cl.person_id
LEFT JOIN current_emp   ce ON ce.person_id = cl.person_id
LEFT JOIN organizations o  ON o.id = ce.organization_id
WHERE cl.campaign_id = $1
ORDER BY cl.created_at DESC
`

type ListCampaignLeadsRow struct {
	ID            pgtype.UUID        `json:"id"`
	CampaignID    pgtype.UUID        `json:"campaign_id"`
	LeadID        pgtype.UUID        `json:"lead_id"`
	PersonID      pgtype.UUID        `json:"person_id"`
	Status        pgtype.Text        `json:"status"`
	CurrentStep   pgtype.Int4        `json:"current_step"`
	NextSendAt    pgtype.Timestamptz `json:"next_send_at"`
	LastSentAt    pgtype.Timestamptz `json:"last_sent_at"`
	LastOpenedAt  pgtype.Timestamptz `json:"last_opened_at"`
	LastRepliedAt pgtype.Timestamptz `json:"last_replied_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Email         string             `json:"email"`
	Title         pgtype.Text        `json:"title"`
	Company       string             `json:"company"`
	LinkedinUrl   pgtype.Text        `json:"linkedin_url"`
}

// ListCampaignLeads returns the rows for one campaign with contact
// fields resolved from either the canonical persons graph (preferred)
// or the legacy leads table. Mirrors GetDueLeads's CTE structure so
// that the UI displays the same unified shape.
func (q *Queries) ListCampaignLeads(ctx context.Context, campaignID pgtype.UUID) ([]ListCampaignLeadsRow, error) {
	rows, err := q.db.Query(ctx, listCampaignLeads, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignLeadsRow{}
	for rows.Next() {
		var i ListCampaignLeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.LeadID,
			&i.PersonID,
			&i.Status,
			&i.CurrentStep,
			&i.NextSendAt,
			&i.LastSentAt,
			&i.LastOpenedAt,
			&i.LastRepliedAt,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Title,
			&i.Company,
			&i.LinkedinUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseCampaignLeads = `-- name: PauseCampaignLeads :exec
UPDATE campaign_leads SET next_send_at = NULL
WHERE campaign_id = $1 AND status = 'active'
`

func (q *Queries) PauseCampaignLeads(ctx context.Context, campaignID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pauseCampaignLeads, campaignID)
	return err
}

const updateCampaignLeadStep = `-- name: UpdateCampaignLeadStep :exec
UPDATE campaign_leads
SET current_step = $2, next_send_at = $3, last_sent_at = NOW(), status = $4
WHERE id = $1
`

type UpdateCampaignLeadStepParams struct {
	ID          pgtype.UUID        `json:"id"`
	CurrentStep pgtype.Int4        `json:"current_step"`
	NextSendAt  pgtype.Timestamptz `json:"next_send_at"`
	Status      pgtype.Text        `json:"status"`
}

func (q *Queries) UpdateCampaignLeadStep(ctx context.Context, arg UpdateCampaignLeadStepParams) error {
	_, err := q.db.Exec(ctx, updateCampaignLeadStep,
		arg.ID,
		arg.CurrentStep,
		arg.NextSendAt,
		arg.Status,
	)
	return err
}
