// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: campaigns.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (tenant_id, play_id, name, status, gmail_account_id, sequence, linkedin_sequence)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, play_id, name, status, gmail_account_id, sequence, linkedin_sequence, stats, created_at
`

type CreateCampaignParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	PlayID           pgtype.UUID `json:"play_id"`
	Name             string      `json:"name"`
	Status           pgtype.Text `json:"status"`
	GmailAccountID   pgtype.UUID `json:"gmail_account_id"`
	Sequence         []byte      `json:"sequence"`
	LinkedinSequence []byte      `json:"linkedin_sequence"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.TenantID,
		arg.PlayID,
		arg.Name,
		arg.Status,
		arg.GmailAccountID,
		arg.Sequence,
		arg.LinkedinSequence,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlayID,
		&i.Name,
		&i.Status,
		&i.GmailAccountID,
		&i.Sequence,
		&i.LinkedinSequence,
		&i.Stats,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, tenant_id, play_id, name, status, gmail_account_id, sequence, linkedin_sequence, stats, created_at FROM campaigns WHERE id = $1 AND tenant_id = $2
`

type GetCampaignParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCampaign(ctx context.Context, arg GetCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, arg.ID, arg.TenantID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlayID,
		&i.Name,
		&i.Status,
		&i.GmailAccountID,
		&i.Sequence,
		&i.LinkedinSequence,
		&i.Stats,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, tenant_id, play_id, name, status, gmail_account_id, sequence, linkedin_sequence, stats, created_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlayID,
		&i.Name,
		&i.Status,
		&i.GmailAccountID,
		&i.Sequence,
		&i.LinkedinSequence,
		&i.Stats,
		&i.CreatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, tenant_id, play_id, name, status, gmail_account_id, sequence, linkedin_sequence, stats, created_at FROM campaigns WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCampaigns(ctx context.Context, tenantID pgtype.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PlayID,
			&i.Name,
			&i.Status,
			&i.GmailAccountID,
			&i.Sequence,
			&i.LinkedinSequence,
			&i.Stats,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignSequence = `-- name: UpdateCampaignSequence :exec
UPDATE campaigns SET sequence = $2 WHERE id = $1
`

type UpdateCampaignSequenceParams struct {
	ID       pgtype.UUID `json:"id"`
	Sequence []byte      `json:"sequence"`
}

func (q *Queries) UpdateCampaignSequence(ctx context.Context, arg UpdateCampaignSequenceParams) error {
	_, err := q.db.Exec(ctx, updateCampaignSequence, arg.ID, arg.Sequence)
	return err
}

const updateCampaignStats = `-- name: UpdateCampaignStats :exec
UPDATE campaigns SET stats = $2 WHERE id = $1
`

type UpdateCampaignStatsParams struct {
	ID    pgtype.UUID `json:"id"`
	Stats []byte      `json:"stats"`
}

func (q *Queries) UpdateCampaignStats(ctx context.Context, arg UpdateCampaignStatsParams) error {
	_, err := q.db.Exec(ctx, updateCampaignStats, arg.ID, arg.Stats)
	return err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns SET status = $2 WHERE id = $1 RETURNING id, tenant_id, play_id, name, status, gmail_account_id, sequence, linkedin_sequence, stats, created_at
`

type UpdateCampaignStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlayID,
		&i.Name,
		&i.Status,
		&i.GmailAccountID,
		&i.Sequence,
		&i.LinkedinSequence,
		&i.Stats,
		&i.CreatedAt,
	)
	return i, err
}
