// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_accounts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailAccount = `-- name: CreateEmailAccount :one
INSERT INTO email_accounts (tenant_id, user_id, provider, email, smtp_host, smtp_port, smtp_username, smtp_password, access_token, refresh_token, token_expiry, sender_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, user_id, provider, email, smtp_host, smtp_port, smtp_username, smtp_password, access_token, refresh_token, token_expiry, sender_name, daily_sent_count, daily_sent_reset_at, is_active, created_at
`

type CreateEmailAccountParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Provider     string             `json:"provider"`
	Email        string             `json:"email"`
	SmtpHost     pgtype.Text        `json:"smtp_host"`
	SmtpPort     pgtype.Int4        `json:"smtp_port"`
	SmtpUsername pgtype.Text        `json:"smtp_username"`
	SmtpPassword pgtype.Text        `json:"smtp_password"`
	AccessToken  pgtype.Text        `json:"access_token"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
	SenderName   pgtype.Text        `json:"sender_name"`
}

func (q *Queries) CreateEmailAccount(ctx context.Context, arg CreateEmailAccountParams) (EmailAccount, error) {
	row := q.db.QueryRow(ctx, createEmailAccount,
		arg.TenantID,
		arg.UserID,
		arg.Provider,
		arg.Email,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpUsername,
		arg.SmtpPassword,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.SenderName,
	)
	var i EmailAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Provider,
		&i.Email,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.SenderName,
		&i.DailySentCount,
		&i.DailySentResetAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailAccount = `-- name: DeleteEmailAccount :exec
DELETE FROM email_accounts WHERE id = $1 AND tenant_id = $2
`

type DeleteEmailAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteEmailAccount(ctx context.Context, arg DeleteEmailAccountParams) error {
	_, err := q.db.Exec(ctx, deleteEmailAccount, arg.ID, arg.TenantID)
	return err
}

const getEmailAccount = `-- name: GetEmailAccount :one
SELECT id, tenant_id, user_id, provider, email, smtp_host, smtp_port, smtp_username, smtp_password, access_token, refresh_token, token_expiry, sender_name, daily_sent_count, daily_sent_reset_at, is_active, created_at FROM email_accounts WHERE id = $1 AND tenant_id = $2
`

type GetEmailAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetEmailAccount(ctx context.Context, arg GetEmailAccountParams) (EmailAccount, error) {
	row := q.db.QueryRow(ctx, getEmailAccount, arg.ID, arg.TenantID)
	var i EmailAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Provider,
		&i.Email,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.SenderName,
		&i.DailySentCount,
		&i.DailySentResetAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const incrementEmailSent = `-- name: IncrementEmailSent :exec
UPDATE email_accounts SET daily_sent_count = daily_sent_count + 1 WHERE id = $1
`

func (q *Queries) IncrementEmailSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementEmailSent, id)
	return err
}

const listEmailAccounts = `-- name: ListEmailAccounts :many
SELECT id, tenant_id, user_id, provider, email, smtp_host, smtp_port, smtp_username, smtp_password, access_token, refresh_token, token_expiry, sender_name, daily_sent_count, daily_sent_reset_at, is_active, created_at FROM email_accounts WHERE tenant_id = $1 AND is_active = TRUE
`

func (q *Queries) ListEmailAccounts(ctx context.Context, tenantID pgtype.UUID) ([]EmailAccount, error) {
	rows, err := q.db.Query(ctx, listEmailAccounts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailAccount{}
	for rows.Next() {
		var i EmailAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Provider,
			&i.Email,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpUsername,
			&i.SmtpPassword,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.SenderName,
			&i.DailySentCount,
			&i.DailySentResetAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetEmailSentCounts = `-- name: ResetEmailSentCounts :exec
UPDATE email_accounts SET daily_sent_count = 0, daily_sent_reset_at = NOW()
WHERE daily_sent_reset_at < CURRENT_DATE
`

func (q *Queries) ResetEmailSentCounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetEmailSentCounts)
	return err
}

const updateEmailAccountTokens = `-- name: UpdateEmailAccountTokens :exec
UPDATE email_accounts SET access_token = $2, refresh_token = $3, token_expiry = $4 WHERE id = $1
`

type UpdateEmailAccountTokensParams struct {
	ID           pgtype.UUID        `json:"id"`
	AccessToken  pgtype.Text        `json:"access_token"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
}

func (q *Queries) UpdateEmailAccountTokens(ctx context.Context, arg UpdateEmailAccountTokensParams) error {
	_, err := q.db.Exec(ctx, updateEmailAccountTokens,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
	)
	return err
}
