// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: email_events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailEvent = `-- name: CreateEmailEvent :one
INSERT INTO email_events (campaign_lead_id, event_type, step, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, campaign_lead_id, event_type, step, metadata, created_at
`

type CreateEmailEventParams struct {
	CampaignLeadID pgtype.UUID `json:"campaign_lead_id"`
	EventType      string      `json:"event_type"`
	Step           int32       `json:"step"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateEmailEvent(ctx context.Context, arg CreateEmailEventParams) (EmailEvent, error) {
	row := q.db.QueryRow(ctx, createEmailEvent,
		arg.CampaignLeadID,
		arg.EventType,
		arg.Step,
		arg.Metadata,
	)
	var i EmailEvent
	err := row.Scan(
		&i.ID,
		&i.CampaignLeadID,
		&i.EventType,
		&i.Step,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listEmailEvents = `-- name: ListEmailEvents :many
SELECT id, campaign_lead_id, event_type, step, metadata, created_at FROM email_events WHERE campaign_lead_id = $1 ORDER BY created_at
`

func (q *Queries) ListEmailEvents(ctx context.Context, campaignLeadID pgtype.UUID) ([]EmailEvent, error) {
	rows, err := q.db.Query(ctx, listEmailEvents, campaignLeadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailEvent{}
	for rows.Next() {
		var i EmailEvent
		if err := rows.Scan(
			&i.ID,
			&i.CampaignLeadID,
			&i.EventType,
			&i.Step,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
