// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailEvent = `-- name: CreateEmailEvent :one
INSERT INTO email_events (campaign_lead_id, event_type, step, metadata, gmail_message_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, campaign_lead_id, event_type, step, metadata, created_at, gmail_message_id
`

type CreateEmailEventParams struct {
	CampaignLeadID pgtype.UUID `json:"campaign_lead_id"`
	EventType      string      `json:"event_type"`
	Step           int32       `json:"step"`
	Metadata       []byte      `json:"metadata"`
	GmailMessageID pgtype.Text `json:"gmail_message_id"`
}

func (q *Queries) CreateEmailEvent(ctx context.Context, arg CreateEmailEventParams) (EmailEvent, error) {
	row := q.db.QueryRow(ctx, createEmailEvent,
		arg.CampaignLeadID,
		arg.EventType,
		arg.Step,
		arg.Metadata,
		arg.GmailMessageID,
	)
	var i EmailEvent
	err := row.Scan(
		&i.ID,
		&i.CampaignLeadID,
		&i.EventType,
		&i.Step,
		&i.Metadata,
		&i.CreatedAt,
		&i.GmailMessageID,
	)
	return i, err
}

const findEmailEventByGmailMessageID = `-- name: FindEmailEventByGmailMessageID :one
SELECT id, campaign_lead_id, event_type, step, metadata, created_at, gmail_message_id FROM email_events
WHERE gmail_message_id = $1
LIMIT 1
`

func (q *Queries) FindEmailEventByGmailMessageID(ctx context.Context, gmailMessageID pgtype.Text) (EmailEvent, error) {
	row := q.db.QueryRow(ctx, findEmailEventByGmailMessageID, gmailMessageID)
	var i EmailEvent
	err := row.Scan(
		&i.ID,
		&i.CampaignLeadID,
		&i.EventType,
		&i.Step,
		&i.Metadata,
		&i.CreatedAt,
		&i.GmailMessageID,
	)
	return i, err
}

const listEmailEvents = `-- name: ListEmailEvents :many
SELECT id, campaign_lead_id, event_type, step, metadata, created_at, gmail_message_id FROM email_events WHERE campaign_lead_id = $1 ORDER BY created_at
`

func (q *Queries) ListEmailEvents(ctx context.Context, campaignLeadID pgtype.UUID) ([]EmailEvent, error) {
	rows, err := q.db.Query(ctx, listEmailEvents, campaignLeadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailEvent{}
	for rows.Next() {
		var i EmailEvent
		if err := rows.Scan(
			&i.ID,
			&i.CampaignLeadID,
			&i.EventType,
			&i.Step,
			&i.Metadata,
			&i.CreatedAt,
			&i.GmailMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailEventsForExport = `-- name: ListEmailEventsForExport :many
SELECT ee.id, ee.campaign_lead_id, ee.event_type, ee.step, ee.metadata, ee.created_at, ee.gmail_message_id
FROM email_events ee
JOIN campaign_leads cl ON cl.id = ee.campaign_lead_id
JOIN campaigns c       ON c.id  = cl.campaign_id
WHERE c.tenant_id = $1
ORDER BY ee.created_at
`

// ListEmailEventsForExport dumps every email_event tied to a tenant
// (via campaign_leads → campaigns). Used by the GDPR account-export
// endpoint (issue #11). Raw rows, oldest first.
func (q *Queries) ListEmailEventsForExport(ctx context.Context, tenantID pgtype.UUID) ([]EmailEvent, error) {
	rows, err := q.db.Query(ctx, listEmailEventsForExport, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailEvent{}
	for rows.Next() {
		var i EmailEvent
		if err := rows.Scan(
			&i.ID,
			&i.CampaignLeadID,
			&i.EventType,
			&i.Step,
			&i.Metadata,
			&i.CreatedAt,
			&i.GmailMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
