// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gmail_accounts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGmailAccount = `-- name: CreateGmailAccount :one
INSERT INTO gmail_accounts (tenant_id, user_id, email, access_token, refresh_token, token_expiry)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, user_id, email, access_token, refresh_token, token_expiry, daily_sent_count, daily_sent_reset_at, created_at
`

type CreateGmailAccountParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Email        string             `json:"email"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
}

func (q *Queries) CreateGmailAccount(ctx context.Context, arg CreateGmailAccountParams) (GmailAccount, error) {
	row := q.db.QueryRow(ctx, createGmailAccount,
		arg.TenantID,
		arg.UserID,
		arg.Email,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
	)
	var i GmailAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.DailySentCount,
		&i.DailySentResetAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGmailAccount = `-- name: DeleteGmailAccount :exec
DELETE FROM gmail_accounts WHERE id = $1 AND tenant_id = $2
`

type DeleteGmailAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteGmailAccount(ctx context.Context, arg DeleteGmailAccountParams) error {
	_, err := q.db.Exec(ctx, deleteGmailAccount, arg.ID, arg.TenantID)
	return err
}

const getGmailAccount = `-- name: GetGmailAccount :one
SELECT id, tenant_id, user_id, email, access_token, refresh_token, token_expiry, daily_sent_count, daily_sent_reset_at, created_at FROM gmail_accounts WHERE id = $1 AND tenant_id = $2
`

type GetGmailAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetGmailAccount(ctx context.Context, arg GetGmailAccountParams) (GmailAccount, error) {
	row := q.db.QueryRow(ctx, getGmailAccount, arg.ID, arg.TenantID)
	var i GmailAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.DailySentCount,
		&i.DailySentResetAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementDailySent = `-- name: IncrementDailySent :exec
UPDATE gmail_accounts SET daily_sent_count = daily_sent_count + 1 WHERE id = $1
`

func (q *Queries) IncrementDailySent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementDailySent, id)
	return err
}

const listGmailAccounts = `-- name: ListGmailAccounts :many
SELECT id, tenant_id, user_id, email, access_token, refresh_token, token_expiry, daily_sent_count, daily_sent_reset_at, created_at FROM gmail_accounts WHERE tenant_id = $1
`

func (q *Queries) ListGmailAccounts(ctx context.Context, tenantID pgtype.UUID) ([]GmailAccount, error) {
	rows, err := q.db.Query(ctx, listGmailAccounts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GmailAccount{}
	for rows.Next() {
		var i GmailAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Email,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.DailySentCount,
			&i.DailySentResetAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDailySentCounts = `-- name: ResetDailySentCounts :exec
UPDATE gmail_accounts SET daily_sent_count = 0, daily_sent_reset_at = NOW()
WHERE daily_sent_reset_at < CURRENT_DATE
`

func (q *Queries) ResetDailySentCounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetDailySentCounts)
	return err
}

const updateGmailTokens = `-- name: UpdateGmailTokens :exec
UPDATE gmail_accounts SET access_token = $2, refresh_token = $3, token_expiry = $4 WHERE id = $1
`

type UpdateGmailTokensParams struct {
	ID           pgtype.UUID        `json:"id"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
}

func (q *Queries) UpdateGmailTokens(ctx context.Context, arg UpdateGmailTokensParams) error {
	_, err := q.db.Exec(ctx, updateGmailTokens,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
	)
	return err
}
