// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConflictQueueItem = `-- name: CreateConflictQueueItem :one
INSERT INTO conflict_queue (canonical_table, canonical_id, new_source_record_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, canonical_table, canonical_id, new_source_record_id, status, created_at
`

type CreateConflictQueueItemParams struct {
	CanonicalTable    string      `json:"canonical_table"`
	CanonicalID       pgtype.UUID `json:"canonical_id"`
	NewSourceRecordID pgtype.UUID `json:"new_source_record_id"`
	Status            string      `json:"status"`
}

func (q *Queries) CreateConflictQueueItem(ctx context.Context, arg CreateConflictQueueItemParams) (ConflictQueue, error) {
	row := q.db.QueryRow(ctx, createConflictQueueItem,
		arg.CanonicalTable,
		arg.CanonicalID,
		arg.NewSourceRecordID,
		arg.Status,
	)
	var i ConflictQueue
	err := row.Scan(
		&i.ID,
		&i.CanonicalTable,
		&i.CanonicalID,
		&i.NewSourceRecordID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createEmployment = `-- name: CreateEmployment :one
INSERT INTO employments (person_id, organization_id, title, start_date, end_date, is_current)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, person_id, organization_id, title, start_date, end_date, is_current, created_at
`

type CreateEmploymentParams struct {
	PersonID       pgtype.UUID `json:"person_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Title          pgtype.Text `json:"title"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	IsCurrent      pgtype.Bool `json:"is_current"`
}

func (q *Queries) CreateEmployment(ctx context.Context, arg CreateEmploymentParams) (Employment, error) {
	row := q.db.QueryRow(ctx, createEmployment,
		arg.PersonID,
		arg.OrganizationID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrent,
	)
	var i Employment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.OrganizationID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
	)
	return i, err
}

const createEvidence = `-- name: CreateEvidence :one
INSERT INTO evidence (canonical_table, canonical_id, source_record_id, confidence, conflict_flag)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, canonical_table, canonical_id, source_record_id, confidence, conflict_flag, resolved_by_user_id, created_at
`

type CreateEvidenceParams struct {
	CanonicalTable string      `json:"canonical_table"`
	CanonicalID    pgtype.UUID `json:"canonical_id"`
	SourceRecordID pgtype.UUID `json:"source_record_id"`
	Confidence     int16       `json:"confidence"`
	ConflictFlag   pgtype.Bool `json:"conflict_flag"`
}

func (q *Queries) CreateEvidence(ctx context.Context, arg CreateEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, createEvidence,
		arg.CanonicalTable,
		arg.CanonicalID,
		arg.SourceRecordID,
		arg.Confidence,
		arg.ConflictFlag,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.CanonicalTable,
		&i.CanonicalID,
		&i.SourceRecordID,
		&i.Confidence,
		&i.ConflictFlag,
		&i.ResolvedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (canonical_name, primary_domain)
VALUES ($1, $2)
RETURNING id, canonical_name, primary_domain, created_at, updated_at, industries, size_range
`

type CreateOrganizationParams struct {
	CanonicalName string      `json:"canonical_name"`
	PrimaryDomain pgtype.Text `json:"primary_domain"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.CanonicalName, arg.PrimaryDomain)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.PrimaryDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Industries,
		&i.SizeRange,
	)
	return i, err
}

const createOrganizationAlias = `-- name: CreateOrganizationAlias :exec
INSERT INTO organization_aliases (organization_id, alias, alias_type)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT organization_aliases_unique DO NOTHING
`

type CreateOrganizationAliasParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Alias          string      `json:"alias"`
	AliasType      string      `json:"alias_type"`
}

func (q *Queries) CreateOrganizationAlias(ctx context.Context, arg CreateOrganizationAliasParams) error {
	_, err := q.db.Exec(ctx, createOrganizationAlias, arg.OrganizationID, arg.Alias, arg.AliasType)
	return err
}

const createOrganizationIdentifier = `-- name: CreateOrganizationIdentifier :exec
INSERT INTO organization_identifiers (organization_id, identifier_type, identifier_value, is_primary)
VALUES ($1, $2, $3, $4)
`

type CreateOrganizationIdentifierParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	IdentifierType  string      `json:"identifier_type"`
	IdentifierValue string      `json:"identifier_value"`
	IsPrimary       pgtype.Bool `json:"is_primary"`
}

func (q *Queries) CreateOrganizationIdentifier(ctx context.Context, arg CreateOrganizationIdentifierParams) error {
	_, err := q.db.Exec(ctx, createOrganizationIdentifier,
		arg.OrganizationID,
		arg.IdentifierType,
		arg.IdentifierValue,
		arg.IsPrimary,
	)
	return err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (canonical_name, first_name, last_name, normalized_name)
VALUES ($1, $2, $3, $4)
RETURNING id, canonical_name, first_name, last_name, created_at, updated_at, normalized_name, location
`

type CreatePersonParams struct {
	CanonicalName  string      `json:"canonical_name"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	NormalizedName string      `json:"normalized_name"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.CanonicalName,
		arg.FirstName,
		arg.LastName,
		arg.NormalizedName,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NormalizedName,
		&i.Location,
	)
	return i, err
}

const createPersonAlias = `-- name: CreatePersonAlias :exec
INSERT INTO person_aliases (person_id, alias, alias_type)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT person_aliases_unique DO NOTHING
`

type CreatePersonAliasParams struct {
	PersonID  pgtype.UUID `json:"person_id"`
	Alias     string      `json:"alias"`
	AliasType string      `json:"alias_type"`
}

func (q *Queries) CreatePersonAlias(ctx context.Context, arg CreatePersonAliasParams) error {
	_, err := q.db.Exec(ctx, createPersonAlias, arg.PersonID, arg.Alias, arg.AliasType)
	return err
}

const createPersonIdentifier = `-- name: CreatePersonIdentifier :exec
INSERT INTO person_identifiers (person_id, identifier_type, identifier_value, is_primary)
VALUES ($1, $2, $3, $4)
`

type CreatePersonIdentifierParams struct {
	PersonID        pgtype.UUID `json:"person_id"`
	IdentifierType  string      `json:"identifier_type"`
	IdentifierValue string      `json:"identifier_value"`
	IsPrimary       pgtype.Bool `json:"is_primary"`
}

func (q *Queries) CreatePersonIdentifier(ctx context.Context, arg CreatePersonIdentifierParams) error {
	_, err := q.db.Exec(ctx, createPersonIdentifier,
		arg.PersonID,
		arg.IdentifierType,
		arg.IdentifierValue,
		arg.IsPrimary,
	)
	return err
}

const createRawIngest = `-- name: CreateRawIngest :one
INSERT INTO raw_ingests (source_id, file_url, checksum, size_bytes, meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, source_id, file_url, ingested_at, checksum, size_bytes, meta
`

type CreateRawIngestParams struct {
	SourceID  pgtype.UUID `json:"source_id"`
	FileUrl   string      `json:"file_url"`
	Checksum  string      `json:"checksum"`
	SizeBytes int64       `json:"size_bytes"`
	Meta      []byte      `json:"meta"`
}

func (q *Queries) CreateRawIngest(ctx context.Context, arg CreateRawIngestParams) (RawIngest, error) {
	row := q.db.QueryRow(ctx, createRawIngest,
		arg.SourceID,
		arg.FileUrl,
		arg.Checksum,
		arg.SizeBytes,
		arg.Meta,
	)
	var i RawIngest
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.FileUrl,
		&i.IngestedAt,
		&i.Checksum,
		&i.SizeBytes,
		&i.Meta,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (name, type, api_endpoint)
VALUES ($1, $2, $3)
RETURNING id, name, type, api_endpoint, last_ingested_at, created_at
`

type CreateSourceParams struct {
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	ApiEndpoint pgtype.Text `json:"api_endpoint"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource, arg.Name, arg.Type, arg.ApiEndpoint)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ApiEndpoint,
		&i.LastIngestedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSourceRecord = `-- name: CreateSourceRecord :one
INSERT INTO source_records (source_id, raw_ingest_id, external_id, fields)
VALUES ($1, $2, $3, $4)
RETURNING id, source_id, raw_ingest_id, external_id, fields, ingested_at
`

type CreateSourceRecordParams struct {
	SourceID    pgtype.UUID `json:"source_id"`
	RawIngestID pgtype.UUID `json:"raw_ingest_id"`
	ExternalID  pgtype.Text `json:"external_id"`
	Fields      []byte      `json:"fields"`
}

func (q *Queries) CreateSourceRecord(ctx context.Context, arg CreateSourceRecordParams) (SourceRecord, error) {
	row := q.db.QueryRow(ctx, createSourceRecord,
		arg.SourceID,
		arg.RawIngestID,
		arg.ExternalID,
		arg.Fields,
	)
	var i SourceRecord
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.RawIngestID,
		&i.ExternalID,
		&i.Fields,
		&i.IngestedAt,
	)
	return i, err
}

const findCurrentEmploymentByTitle = `-- name: FindCurrentEmploymentByTitle :one
SELECT id, person_id, organization_id, title, start_date, end_date, is_current, created_at FROM employments
WHERE person_id = $1
  AND organization_id = $2
  AND is_current = TRUE
  AND title IS NOT DISTINCT FROM $3
LIMIT 1
`

type FindCurrentEmploymentByTitleParams struct {
	PersonID       pgtype.UUID `json:"person_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Title          pgtype.Text `json:"title"`
}

func (q *Queries) FindCurrentEmploymentByTitle(ctx context.Context, arg FindCurrentEmploymentByTitleParams) (Employment, error) {
	row := q.db.QueryRow(ctx, findCurrentEmploymentByTitle, arg.PersonID, arg.OrganizationID, arg.Title)
	var i Employment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.OrganizationID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
	)
	return i, err
}

const findOrganizationByIdentifier = `-- name: FindOrganizationByIdentifier :one
SELECT o.id, o.canonical_name, o.primary_domain, o.created_at, o.updated_at, o.industries, o.size_range
FROM organizations o
JOIN organization_identifiers oi ON oi.organization_id = o.id
WHERE oi.identifier_type = $1 AND oi.identifier_value = $2
LIMIT 1
`

type FindOrganizationByIdentifierParams struct {
	IdentifierType  string `json:"identifier_type"`
	IdentifierValue string `json:"identifier_value"`
}

func (q *Queries) FindOrganizationByIdentifier(ctx context.Context, arg FindOrganizationByIdentifierParams) (Organization, error) {
	row := q.db.QueryRow(ctx, findOrganizationByIdentifier, arg.IdentifierType, arg.IdentifierValue)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.PrimaryDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Industries,
		&i.SizeRange,
	)
	return i, err
}

const findPersonByIdentifier = `-- name: FindPersonByIdentifier :one
SELECT p.id, p.canonical_name, p.first_name, p.last_name, p.created_at, p.updated_at, p.normalized_name, p.location
FROM persons p
JOIN person_identifiers pi ON pi.person_id = p.id
WHERE pi.identifier_type = $1 AND pi.identifier_value = $2
LIMIT 1
`

type FindPersonByIdentifierParams struct {
	IdentifierType  string `json:"identifier_type"`
	IdentifierValue string `json:"identifier_value"`
}

func (q *Queries) FindPersonByIdentifier(ctx context.Context, arg FindPersonByIdentifierParams) (Person, error) {
	row := q.db.QueryRow(ctx, findPersonByIdentifier, arg.IdentifierType, arg.IdentifierValue)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NormalizedName,
		&i.Location,
	)
	return i, err
}

const findPersonsByNameAtOrg = `-- name: FindPersonsByNameAtOrg :many
SELECT p.id, similarity(p.canonical_name, $1::text)::real AS sim
FROM persons p
WHERE p.canonical_name % $1::text
  AND EXISTS (
    SELECT 1 FROM employments e
    WHERE e.person_id = p.id AND e.organization_id = $2
  )
ORDER BY similarity(p.canonical_name, $1::text) DESC
LIMIT 5
`

type FindPersonsByNameAtOrgParams struct {
	QueryName      string      `json:"query_name"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type FindPersonsByNameAtOrgRow struct {
	ID  pgtype.UUID `json:"id"`
	Sim float32     `json:"sim"`
}

// FindPersonsByNameAtOrg returns persons with fuzzy-matching canonical
// names who have at least one employment at the given organization,
// sorted by similarity. Uses the GIN trgm index via `%`.
func (q *Queries) FindPersonsByNameAtOrg(ctx context.Context, arg FindPersonsByNameAtOrgParams) ([]FindPersonsByNameAtOrgRow, error) {
	rows, err := q.db.Query(ctx, findPersonsByNameAtOrg, arg.QueryName, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPersonsByNameAtOrgRow{}
	for rows.Next() {
		var i FindPersonsByNameAtOrgRow
		if err := rows.Scan(&i.ID, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPersonsByNormalizedName = `-- name: FindPersonsByNormalizedName :many
SELECT p.id, similarity(p.normalized_name, $1::text)::real AS sim
FROM persons p
WHERE p.normalized_name % $1::text
ORDER BY similarity(p.normalized_name, $1::text) DESC
LIMIT 5
`

type FindPersonsByNormalizedNameRow struct {
	ID  pgtype.UUID `json:"id"`
	Sim float32     `json:"sim"`
}

// FindPersonsByNormalizedName does a cross-org fuzzy match — used for
// T08 when neither CIK nor LinkedIn identified the person and an
// at-org fuzzy match came up empty.
func (q *Queries) FindPersonsByNormalizedName(ctx context.Context, queryName string) ([]FindPersonsByNormalizedNameRow, error) {
	rows, err := q.db.Query(ctx, findPersonsByNormalizedName, queryName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPersonsByNormalizedNameRow{}
	for rows.Next() {
		var i FindPersonsByNormalizedNameRow
		if err := rows.Scan(&i.ID, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRawIngestByChecksum = `-- name: GetRawIngestByChecksum :one
SELECT id, source_id, file_url, ingested_at, checksum, size_bytes, meta FROM raw_ingests
WHERE source_id = $1 AND checksum = $2
LIMIT 1
`

type GetRawIngestByChecksumParams struct {
	SourceID pgtype.UUID `json:"source_id"`
	Checksum string      `json:"checksum"`
}

func (q *Queries) GetRawIngestByChecksum(ctx context.Context, arg GetRawIngestByChecksumParams) (RawIngest, error) {
	row := q.db.QueryRow(ctx, getRawIngestByChecksum, arg.SourceID, arg.Checksum)
	var i RawIngest
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.FileUrl,
		&i.IngestedAt,
		&i.Checksum,
		&i.SizeBytes,
		&i.Meta,
	)
	return i, err
}

const getSourceByName = `-- name: GetSourceByName :one
SELECT id, name, type, api_endpoint, last_ingested_at, created_at FROM sources WHERE name = $1
`

func (q *Queries) GetSourceByName(ctx context.Context, name string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByName, name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ApiEndpoint,
		&i.LastIngestedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchSourceLastIngested = `-- name: TouchSourceLastIngested :exec
UPDATE sources SET last_ingested_at = NOW() WHERE id = $1
`

func (q *Queries) TouchSourceLastIngested(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSourceLastIngested, id)
	return err
}

const updatePersonNormalizedName = `-- name: UpdatePersonNormalizedName :exec
UPDATE persons SET normalized_name = $2 WHERE id = $1
`

type UpdatePersonNormalizedNameParams struct {
	ID             pgtype.UUID `json:"id"`
	NormalizedName string      `json:"normalized_name"`
}

func (q *Queries) UpdatePersonNormalizedName(ctx context.Context, arg UpdatePersonNormalizedNameParams) error {
	_, err := q.db.Exec(ctx, updatePersonNormalizedName, arg.ID, arg.NormalizedName)
	return err
}
