// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lead_search.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBestEmailsForPersons = `-- name: ListBestEmailsForPersons :many

SELECT DISTINCT ON (em.person_id)
    em.person_id,
    em.email,
    em.verified_at,
    em.is_catchall,
    em.bounce_count,
    em.verification_method
FROM emails em
WHERE em.person_id = ANY($1::uuid[])
ORDER BY em.person_id,
         (em.verified_at IS NOT NULL) DESC,
         em.bounce_count ASC,
         em.created_at ASC
`

type ListBestEmailsForPersonsRow struct {
	PersonID           pgtype.UUID        `json:"person_id"`
	Email              string             `json:"email"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	IsCatchall         pgtype.Bool        `json:"is_catchall"`
	BounceCount        pgtype.Int4        `json:"bounce_count"`
	VerificationMethod pgtype.Text        `json:"verification_method"`
}

// ListBestEmailsForPersons returns the highest-priority email per
// person from the input UUID set: prefer verified, then fewest
// bounces, then oldest. Only persons with at least one email appear
// in the result. Used by the search handler to attach contact data.
func (q *Queries) ListBestEmailsForPersons(ctx context.Context, personIds []pgtype.UUID) ([]ListBestEmailsForPersonsRow, error) {
	rows, err := q.db.Query(ctx, listBestEmailsForPersons, personIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBestEmailsForPersonsRow{}
	for rows.Next() {
		var i ListBestEmailsForPersonsRow
		if err := rows.Scan(
			&i.PersonID,
			&i.Email,
			&i.VerifiedAt,
			&i.IsCatchall,
			&i.BounceCount,
			&i.VerificationMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPersons = `-- name: SearchPersons :many

SELECT
    p.id              AS person_id,
    p.canonical_name  AS person_canonical_name,
    p.first_name,
    p.last_name,
    p.location,
    e.title,
    o.id              AS organization_id,
    o.canonical_name  AS organization_name,
    o.primary_domain,
    o.industries,
    o.size_range,
    COALESCE(
        (SELECT MAX(similarity(e.title, t))
         FROM unnest(COALESCE($1::text[], ARRAY[]::text[])) AS t),
        0
    )::real           AS title_score
FROM employments e
JOIN persons p
    ON p.id = e.person_id
JOIN organizations o
    ON o.id = e.organization_id
WHERE
    e.is_current = TRUE
    AND ($1::text[] IS NULL OR EXISTS (
        SELECT 1
        FROM unnest($1::text[]) AS t
        WHERE e.title % t
    ))
    AND (NOT $2::boolean OR EXISTS (
        SELECT 1 FROM emails em
        WHERE em.person_id = p.id AND em.verified_at IS NOT NULL
    ))
    AND ($3::text[] IS NULL OR o.industries && $3::text[])
    AND ($4::text IS NULL OR o.size_range = $4::text)
    AND ($5::text[] IS NULL OR EXISTS (
        SELECT 1
        FROM unnest($5::text[]) AS loc
        WHERE p.location ILIKE '%' || loc || '%'
    ))
    AND (NOT $6::boolean
         OR p.updated_at > NOW() - INTERVAL '90 days')
ORDER BY title_score DESC NULLS LAST,
         p.canonical_name ASC,
         p.id ASC
LIMIT $8 OFFSET $7
`

type SearchPersonsParams struct {
	Titles       []string    `json:"titles"`
	WithEmail    bool        `json:"with_email"`
	Industries   []string    `json:"industries"`
	CompanySize  pgtype.Text `json:"company_size"`
	Locations    []string    `json:"locations"`
	RequireFresh bool        `json:"require_fresh"`
	ResultOffset int32       `json:"result_offset"`
	ResultLimit  int32       `json:"result_limit"`
}

type SearchPersonsRow struct {
	PersonID            pgtype.UUID `json:"person_id"`
	PersonCanonicalName string      `json:"person_canonical_name"`
	FirstName           pgtype.Text `json:"first_name"`
	LastName            pgtype.Text `json:"last_name"`
	Location            pgtype.Text `json:"location"`
	Title               pgtype.Text `json:"title"`
	OrganizationID      pgtype.UUID `json:"organization_id"`
	OrganizationName    string      `json:"organization_name"`
	PrimaryDomain       pgtype.Text `json:"primary_domain"`
	Industries          []string    `json:"industries"`
	SizeRange           pgtype.Text `json:"size_range"`
	TitleScore          float32     `json:"title_score"`
}

// SearchPersons returns canonical persons matching the request
// filters, joined to their current employment and employer, ranked
// by title similarity (pg_trgm) when titles are provided. The handler
// runs ListBestEmailsForPersons in a second roundtrip to attach
// email/verified/catchall fields per result — sqlc 1.28 doesn't
// infer nullability through LEFT JOIN or scalar subqueries, so
// splitting the query keeps both sides cleanly typed.
//
// Per plan §T12 + issue #7 (PDL integration). When industries,
// company_size, locations, or require_fresh is supplied, the query
// gates results to canonical rows that match the PDL filter
// dimensions (industries on organizations, size_range, person
// location) and to rows whose updated_at falls within the 90-day
// staleness window. If the result is empty the handler then routes
// to PDL and re-queries.
//
// Performance: title fuzzy match rides the GIN trgm index on
// employments.title; is_current uses the partial index. The email
// EXISTS check uses idx_emails_person_id. Sub-500ms target on 500K
// persons per plan §6.
func (q *Queries) SearchPersons(ctx context.Context, arg SearchPersonsParams) ([]SearchPersonsRow, error) {
	rows, err := q.db.Query(ctx, searchPersons,
		arg.Titles,
		arg.WithEmail,
		arg.Industries,
		arg.CompanySize,
		arg.Locations,
		arg.RequireFresh,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPersonsRow{}
	for rows.Next() {
		var i SearchPersonsRow
		if err := rows.Scan(
			&i.PersonID,
			&i.PersonCanonicalName,
			&i.FirstName,
			&i.LastName,
			&i.Location,
			&i.Title,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.PrimaryDomain,
			&i.Industries,
			&i.SizeRange,
			&i.TitleScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
