// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: leads.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLead = `-- name: CreateLead :one
INSERT INTO leads (linkedin_url, first_name, last_name, title, company, company_domain, location, email, email_verified, source, raw_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (linkedin_url) DO UPDATE SET
    title = EXCLUDED.title,
    company = EXCLUDED.company,
    email = COALESCE(EXCLUDED.email, leads.email),
    enriched_at = NOW()
RETURNING id, linkedin_url, first_name, last_name, title, company, company_domain, location, email, email_verified, email_verified_at, enriched_at, source, raw_data, created_at, person_id
`

type CreateLeadParams struct {
	LinkedinUrl   pgtype.Text `json:"linkedin_url"`
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
	Title         pgtype.Text `json:"title"`
	Company       pgtype.Text `json:"company"`
	CompanyDomain pgtype.Text `json:"company_domain"`
	Location      pgtype.Text `json:"location"`
	Email         pgtype.Text `json:"email"`
	EmailVerified pgtype.Bool `json:"email_verified"`
	Source        pgtype.Text `json:"source"`
	RawData       []byte      `json:"raw_data"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.LinkedinUrl,
		arg.FirstName,
		arg.LastName,
		arg.Title,
		arg.Company,
		arg.CompanyDomain,
		arg.Location,
		arg.Email,
		arg.EmailVerified,
		arg.Source,
		arg.RawData,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.LinkedinUrl,
		&i.FirstName,
		&i.LastName,
		&i.Title,
		&i.Company,
		&i.CompanyDomain,
		&i.Location,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.EnrichedAt,
		&i.Source,
		&i.RawData,
		&i.CreatedAt,
		&i.PersonID,
	)
	return i, err
}

const getLead = `-- name: GetLead :one
SELECT id, linkedin_url, first_name, last_name, title, company, company_domain, location, email, email_verified, email_verified_at, enriched_at, source, raw_data, created_at, person_id FROM leads WHERE id = $1
`

func (q *Queries) GetLead(ctx context.Context, id pgtype.UUID) (Lead, error) {
	row := q.db.QueryRow(ctx, getLead, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.LinkedinUrl,
		&i.FirstName,
		&i.LastName,
		&i.Title,
		&i.Company,
		&i.CompanyDomain,
		&i.Location,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.EnrichedAt,
		&i.Source,
		&i.RawData,
		&i.CreatedAt,
		&i.PersonID,
	)
	return i, err
}

const listLeads = `-- name: ListLeads :many
SELECT id, linkedin_url, first_name, last_name, title, company, company_domain, location, email, email_verified, email_verified_at, enriched_at, source, raw_data, created_at, person_id FROM leads
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListLeadsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeads, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.LinkedinUrl,
			&i.FirstName,
			&i.LastName,
			&i.Title,
			&i.Company,
			&i.CompanyDomain,
			&i.Location,
			&i.Email,
			&i.EmailVerified,
			&i.EmailVerifiedAt,
			&i.EnrichedAt,
			&i.Source,
			&i.RawData,
			&i.CreatedAt,
			&i.PersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsByIDs = `-- name: ListLeadsByIDs :many
SELECT id, linkedin_url, first_name, last_name, title, company, company_domain, location, email, email_verified, email_verified_at, enriched_at, source, raw_data, created_at, person_id FROM leads WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListLeadsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.LinkedinUrl,
			&i.FirstName,
			&i.LastName,
			&i.Title,
			&i.Company,
			&i.CompanyDomain,
			&i.Location,
			&i.Email,
			&i.EmailVerified,
			&i.EmailVerifiedAt,
			&i.EnrichedAt,
			&i.Source,
			&i.RawData,
			&i.CreatedAt,
			&i.PersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLeads = `-- name: SearchLeads :many
SELECT id, linkedin_url, first_name, last_name, title, company, company_domain, location, email, email_verified, email_verified_at, enriched_at, source, raw_data, created_at, person_id FROM leads
WHERE (first_name ILIKE '%' || $1 || '%' OR last_name ILIKE '%' || $1 || '%' OR company ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchLeadsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchLeads(ctx context.Context, arg SearchLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, searchLeads, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.LinkedinUrl,
			&i.FirstName,
			&i.LastName,
			&i.Title,
			&i.Company,
			&i.CompanyDomain,
			&i.Location,
			&i.Email,
			&i.EmailVerified,
			&i.EmailVerifiedAt,
			&i.EnrichedAt,
			&i.Source,
			&i.RawData,
			&i.CreatedAt,
			&i.PersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
