// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lead_searches.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLeadSearch = `-- name: CreateLeadSearch :one
INSERT INTO lead_searches (query_hash, filters, result_lead_ids, fetched_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, query_hash, filters, result_lead_ids, fetched_at, ttl_days, created_at
`

type CreateLeadSearchParams struct {
	QueryHash     string        `json:"query_hash"`
	Filters       []byte        `json:"filters"`
	ResultLeadIds []pgtype.UUID `json:"result_lead_ids"`
}

func (q *Queries) CreateLeadSearch(ctx context.Context, arg CreateLeadSearchParams) (LeadSearch, error) {
	row := q.db.QueryRow(ctx, createLeadSearch, arg.QueryHash, arg.Filters, arg.ResultLeadIds)
	var i LeadSearch
	err := row.Scan(
		&i.ID,
		&i.QueryHash,
		&i.Filters,
		&i.ResultLeadIds,
		&i.FetchedAt,
		&i.TtlDays,
		&i.CreatedAt,
	)
	return i, err
}

const getCachedSearch = `-- name: GetCachedSearch :one
SELECT id, query_hash, filters, result_lead_ids, fetched_at, ttl_days, created_at FROM lead_searches
WHERE query_hash = $1
AND fetched_at > NOW() - (ttl_days || ' days')::interval
ORDER BY fetched_at DESC
LIMIT 1
`

func (q *Queries) GetCachedSearch(ctx context.Context, queryHash string) (LeadSearch, error) {
	row := q.db.QueryRow(ctx, getCachedSearch, queryHash)
	var i LeadSearch
	err := row.Scan(
		&i.ID,
		&i.QueryHash,
		&i.Filters,
		&i.ResultLeadIds,
		&i.FetchedAt,
		&i.TtlDays,
		&i.CreatedAt,
	)
	return i, err
}
