// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lead_search.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBestEmailsForPersons = `-- name: ListBestEmailsForPersons :many

SELECT DISTINCT ON (em.person_id)
    em.person_id,
    em.email,
    em.verified_at,
    em.is_catchall,
    em.bounce_count
FROM emails em
WHERE em.person_id = ANY($1::uuid[])
ORDER BY em.person_id,
         (em.verified_at IS NOT NULL) DESC,
         em.bounce_count ASC,
         em.created_at ASC
`

type ListBestEmailsForPersonsRow struct {
	PersonID    pgtype.UUID        `json:"person_id"`
	Email       string             `json:"email"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	IsCatchall  pgtype.Bool        `json:"is_catchall"`
	BounceCount pgtype.Int4        `json:"bounce_count"`
}

// ListBestEmailsForPersons returns the highest-priority email per
// person from the input UUID set: prefer verified, then fewest
// bounces, then oldest. Only persons with at least one email appear
// in the result. Used by the search handler to attach contact data.
func (q *Queries) ListBestEmailsForPersons(ctx context.Context, personIds []pgtype.UUID) ([]ListBestEmailsForPersonsRow, error) {
	rows, err := q.db.Query(ctx, listBestEmailsForPersons, personIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBestEmailsForPersonsRow{}
	for rows.Next() {
		var i ListBestEmailsForPersonsRow
		if err := rows.Scan(
			&i.PersonID,
			&i.Email,
			&i.VerifiedAt,
			&i.IsCatchall,
			&i.BounceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPersons = `-- name: SearchPersons :many

SELECT
    p.id              AS person_id,
    p.canonical_name  AS person_canonical_name,
    p.first_name,
    p.last_name,
    e.title,
    o.id              AS organization_id,
    o.canonical_name  AS organization_name,
    o.primary_domain,
    COALESCE(
        (SELECT MAX(similarity(e.title, t))
         FROM unnest(COALESCE($1::text[], ARRAY[]::text[])) AS t),
        0
    )::real           AS title_score
FROM employments e
JOIN persons p
    ON p.id = e.person_id
JOIN organizations o
    ON o.id = e.organization_id
WHERE
    e.is_current = TRUE
    AND ($1::text[] IS NULL OR EXISTS (
        SELECT 1
        FROM unnest($1::text[]) AS t
        WHERE e.title % t
    ))
    AND (NOT $2::boolean OR EXISTS (
        SELECT 1 FROM emails em
        WHERE em.person_id = p.id AND em.verified_at IS NOT NULL
    ))
ORDER BY title_score DESC NULLS LAST,
         p.canonical_name ASC,
         p.id ASC
LIMIT $4 OFFSET $3
`

type SearchPersonsParams struct {
	Titles       []string `json:"titles"`
	WithEmail    bool     `json:"with_email"`
	ResultOffset int32    `json:"result_offset"`
	ResultLimit  int32    `json:"result_limit"`
}

type SearchPersonsRow struct {
	PersonID            pgtype.UUID `json:"person_id"`
	PersonCanonicalName string      `json:"person_canonical_name"`
	FirstName           pgtype.Text `json:"first_name"`
	LastName            pgtype.Text `json:"last_name"`
	Title               pgtype.Text `json:"title"`
	OrganizationID      pgtype.UUID `json:"organization_id"`
	OrganizationName    string      `json:"organization_name"`
	PrimaryDomain       pgtype.Text `json:"primary_domain"`
	TitleScore          float32     `json:"title_score"`
}

// SearchPersons returns canonical persons matching the request
// filters, joined to their current employment and employer, ranked
// by title similarity (pg_trgm) when titles are provided. The handler
// runs ListBestEmailsForPersons in a second roundtrip to attach
// email/verified/catchall fields per result — sqlc 1.28 doesn't
// infer nullability through LEFT JOIN or scalar subqueries, so
// splitting the query keeps both sides cleanly typed.
//
// Per plan §T12. The plan spec also lists industries, company_size,
// and locations — those columns don't exist in the schema yet, so
// those filters are intentionally omitted.
//
// Performance: title fuzzy match rides the GIN trgm index on
// employments.title; is_current uses the partial index. The email
// EXISTS check uses idx_emails_person_id. Sub-500ms target on 500K
// persons per plan §6.
func (q *Queries) SearchPersons(ctx context.Context, arg SearchPersonsParams) ([]SearchPersonsRow, error) {
	rows, err := q.db.Query(ctx, searchPersons,
		arg.Titles,
		arg.WithEmail,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPersonsRow{}
	for rows.Next() {
		var i SearchPersonsRow
		if err := rows.Scan(
			&i.PersonID,
			&i.PersonCanonicalName,
			&i.FirstName,
			&i.LastName,
			&i.Title,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.PrimaryDomain,
			&i.TitleScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
