// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: linkedin_accounts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConnectedLinkedInAccounts = `-- name: CountConnectedLinkedInAccounts :one
SELECT count(*) FROM linkedin_accounts
WHERE tenant_id = $1 AND status NOT IN ('restricted', 'disconnected')
`

// The free-tier connect gate: counts only accounts that occupy the one
// account slot — connecting, active, or warming. An unhealthy account
// (restricted or disconnected) does NOT block the user from re-running the
// connect flow to recover it (issue #8): reconnecting the same account
// upserts it back to active in place (ON CONFLICT on unipile_account_id),
// so the gate must let the reconnect auth-url through rather than 403 it.
func (q *Queries) CountConnectedLinkedInAccounts(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConnectedLinkedInAccounts, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLinkedInAccount = `-- name: DeleteLinkedInAccount :exec
DELETE FROM linkedin_accounts WHERE id = $1 AND tenant_id = $2
`

type DeleteLinkedInAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteLinkedInAccount(ctx context.Context, arg DeleteLinkedInAccountParams) error {
	_, err := q.db.Exec(ctx, deleteLinkedInAccount, arg.ID, arg.TenantID)
	return err
}

const getLinkedInAcceptanceStats = `-- name: GetLinkedInAcceptanceStats :one
SELECT
    COUNT(*) FILTER (WHERE e.event_type = 'invite_sent') AS invites_sent,
    COUNT(*) FILTER (WHERE e.event_type = 'accepted')    AS accepted
FROM linkedin_events e
JOIN campaign_leads cl ON cl.id = e.campaign_lead_id
WHERE cl.linkedin_account_id = $1
  AND e.created_at >= NOW() - INTERVAL '7 days'
`

type GetLinkedInAcceptanceStatsRow struct {
	InvitesSent int64 `json:"invites_sent"`
	Accepted    int64 `json:"accepted"`
}

// GetLinkedInAcceptanceStats returns one account's trailing-7-day invite
// outcomes straight from linkedin_events — invites sent vs invites accepted
// — the raw signal the pacer's acceptance-rate breaker (issue #7) divides.
// Events are keyed by campaign_lead, so we join back to the lead to scope
// them to this account. The 7-day window matches the breaker's trailing
// window; counting in SQL keeps the pure pacer free of any DB of its own.
func (q *Queries) GetLinkedInAcceptanceStats(ctx context.Context, linkedinAccountID pgtype.UUID) (GetLinkedInAcceptanceStatsRow, error) {
	row := q.db.QueryRow(ctx, getLinkedInAcceptanceStats, linkedinAccountID)
	var i GetLinkedInAcceptanceStatsRow
	err := row.Scan(&i.InvitesSent, &i.Accepted)
	return i, err
}

const getLinkedInAccount = `-- name: GetLinkedInAccount :one
SELECT id, tenant_id, unipile_account_id, status, warmup_started_at, weekly_invite_count, weekly_window_started_at, daily_invite_count, daily_reset_at, acceptance_rate, last_error, created_at, acceptance_paused FROM linkedin_accounts WHERE id = $1 AND tenant_id = $2
`

type GetLinkedInAccountParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetLinkedInAccount(ctx context.Context, arg GetLinkedInAccountParams) (LinkedinAccount, error) {
	row := q.db.QueryRow(ctx, getLinkedInAccount, arg.ID, arg.TenantID)
	var i LinkedinAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnipileAccountID,
		&i.Status,
		&i.WarmupStartedAt,
		&i.WeeklyInviteCount,
		&i.WeeklyWindowStartedAt,
		&i.DailyInviteCount,
		&i.DailyResetAt,
		&i.AcceptanceRate,
		&i.LastError,
		&i.CreatedAt,
		&i.AcceptancePaused,
	)
	return i, err
}

const incrementLinkedInInviteCounters = `-- name: IncrementLinkedInInviteCounters :exec
UPDATE linkedin_accounts SET
    weekly_window_started_at = CASE
        WHEN weekly_window_started_at IS NULL
          OR weekly_window_started_at < NOW() - INTERVAL '7 days'
        THEN NOW() ELSE weekly_window_started_at END,
    weekly_invite_count = CASE
        WHEN weekly_window_started_at IS NULL
          OR weekly_window_started_at < NOW() - INTERVAL '7 days'
        THEN 1 ELSE weekly_invite_count + 1 END,
    daily_reset_at = CASE
        WHEN daily_reset_at IS NULL
          OR daily_reset_at < NOW() - INTERVAL '1 day'
        THEN NOW() ELSE daily_reset_at END,
    daily_invite_count = CASE
        WHEN daily_reset_at IS NULL
          OR daily_reset_at < NOW() - INTERVAL '1 day'
        THEN 1 ELSE daily_invite_count + 1 END
WHERE id = $1
`

// IncrementLinkedInInviteCounters records one sent invite against the
// account's rolling caps, resetting a window in the same statement when
// it has rolled over. Both timestamps are window-START markers: the
// weekly window runs [weekly_window_started_at, +7d) and the daily window
// runs [daily_reset_at, +24h). When the current window is NULL or older
// than its span, this send opens a fresh window (count = 1); otherwise it
// bumps the count. The pacer (internal/linkedin/pacer) reads these same
// fields with the same window semantics to decide allowance, so writer
// and reader never disagree. Counting in the DB keeps a within-tick burst
// correct: each send updates the row, so re-reading before the next send
// sees the new count.
func (q *Queries) IncrementLinkedInInviteCounters(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementLinkedInInviteCounters, id)
	return err
}

const listLinkedInAccounts = `-- name: ListLinkedInAccounts :many
SELECT id, tenant_id, unipile_account_id, status, warmup_started_at, weekly_invite_count, weekly_window_started_at, daily_invite_count, daily_reset_at, acceptance_rate, last_error, created_at, acceptance_paused FROM linkedin_accounts WHERE tenant_id = $1 ORDER BY created_at
`

func (q *Queries) ListLinkedInAccounts(ctx context.Context, tenantID pgtype.UUID) ([]LinkedinAccount, error) {
	rows, err := q.db.Query(ctx, listLinkedInAccounts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkedinAccount{}
	for rows.Next() {
		var i LinkedinAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UnipileAccountID,
			&i.Status,
			&i.WarmupStartedAt,
			&i.WeeklyInviteCount,
			&i.WeeklyWindowStartedAt,
			&i.DailyInviteCount,
			&i.DailyResetAt,
			&i.AcceptanceRate,
			&i.LastError,
			&i.CreatedAt,
			&i.AcceptancePaused,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedInAccountsForReconcile = `-- name: ListLinkedInAccountsForReconcile :many
SELECT id, tenant_id, unipile_account_id, status, warmup_started_at, weekly_invite_count, weekly_window_started_at, daily_invite_count, daily_reset_at, acceptance_rate, last_error, created_at, acceptance_paused FROM linkedin_accounts
WHERE status IN ('active', 'warming')
ORDER BY created_at
`

// ListLinkedInAccountsForReconcile returns every account the reconcile
// poll should sweep — those that can still act (active / warming).
// Platform-wide (not tenant-scoped), the LinkedIn analogue of
// ListGmailAccountsForPolling. Restricted / disconnected / connecting
// accounts can't yield new accepts or replies, so they're skipped.
func (q *Queries) ListLinkedInAccountsForReconcile(ctx context.Context) ([]LinkedinAccount, error) {
	rows, err := q.db.Query(ctx, listLinkedInAccountsForReconcile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkedinAccount{}
	for rows.Next() {
		var i LinkedinAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UnipileAccountID,
			&i.Status,
			&i.WarmupStartedAt,
			&i.WeeklyInviteCount,
			&i.WeeklyWindowStartedAt,
			&i.DailyInviteCount,
			&i.DailyResetAt,
			&i.AcceptanceRate,
			&i.LastError,
			&i.CreatedAt,
			&i.AcceptancePaused,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLinkedInAcceptanceState = `-- name: SetLinkedInAcceptanceState :exec
UPDATE linkedin_accounts
SET acceptance_paused = $2, acceptance_rate = $3
WHERE id = $1
`

type SetLinkedInAcceptanceStateParams struct {
	ID               pgtype.UUID `json:"id"`
	AcceptancePaused bool        `json:"acceptance_paused"`
	AcceptanceRate   float64     `json:"acceptance_rate"`
}

// SetLinkedInAcceptanceState records the acceptance-rate breaker's verdict
// for an account (issue #7): whether its invites are paused and the computed
// trailing-7-day rate behind that call, so the UI can show both the pause
// and the number that caused it. The worker writes it only when the paused
// flag flips, so there is no per-tick churn.
func (q *Queries) SetLinkedInAcceptanceState(ctx context.Context, arg SetLinkedInAcceptanceStateParams) error {
	_, err := q.db.Exec(ctx, setLinkedInAcceptanceState, arg.ID, arg.AcceptancePaused, arg.AcceptanceRate)
	return err
}

const setLinkedInAccountStatusByUnipileID = `-- name: SetLinkedInAccountStatusByUnipileID :exec
UPDATE linkedin_accounts SET status = $2, last_error = $3
WHERE unipile_account_id = $1
`

type SetLinkedInAccountStatusByUnipileIDParams struct {
	UnipileAccountID string      `json:"unipile_account_id"`
	Status           string      `json:"status"`
	LastError        pgtype.Text `json:"last_error"`
}

func (q *Queries) SetLinkedInAccountStatusByUnipileID(ctx context.Context, arg SetLinkedInAccountStatusByUnipileIDParams) error {
	_, err := q.db.Exec(ctx, setLinkedInAccountStatusByUnipileID, arg.UnipileAccountID, arg.Status, arg.LastError)
	return err
}

const startLinkedInWarmup = `-- name: StartLinkedInWarmup :exec
UPDATE linkedin_accounts
SET warmup_started_at = COALESCE(warmup_started_at, NOW())
WHERE id = $1
`

// StartLinkedInWarmup anchors an account's warmup ramp the first time the
// worker sends from it: warmup_started_at is set to NOW() only while still
// NULL (COALESCE), so it is fixed once and never reset. The connect handler
// (issue #1) lands accounts active without a warmup anchor, so the send tick
// stamps it here — "warmup begins at first outreach" — and the pacer's ramp
// (internal/linkedin/pacer) reads it from then on. Idempotent: a no-op once set.
func (q *Queries) StartLinkedInWarmup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, startLinkedInWarmup, id)
	return err
}

const upsertLinkedInAccount = `-- name: UpsertLinkedInAccount :one
INSERT INTO linkedin_accounts (tenant_id, unipile_account_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (unipile_account_id) DO UPDATE
SET status = EXCLUDED.status, last_error = NULL
RETURNING id, tenant_id, unipile_account_id, status, warmup_started_at, weekly_invite_count, weekly_window_started_at, daily_invite_count, daily_reset_at, acceptance_rate, last_error, created_at, acceptance_paused
`

type UpsertLinkedInAccountParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	UnipileAccountID string      `json:"unipile_account_id"`
	Status           string      `json:"status"`
}

// Idempotent connect ingest: a replayed account.connected webhook for
// the same Unipile account updates status in place rather than inserting
// a duplicate. tenant_id is fixed on first insert and never reassigned
// on conflict, so a replayed webhook can't move an account between
// tenants.
func (q *Queries) UpsertLinkedInAccount(ctx context.Context, arg UpsertLinkedInAccountParams) (LinkedinAccount, error) {
	row := q.db.QueryRow(ctx, upsertLinkedInAccount, arg.TenantID, arg.UnipileAccountID, arg.Status)
	var i LinkedinAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnipileAccountID,
		&i.Status,
		&i.WarmupStartedAt,
		&i.WeeklyInviteCount,
		&i.WeeklyWindowStartedAt,
		&i.DailyInviteCount,
		&i.DailyResetAt,
		&i.AcceptanceRate,
		&i.LastError,
		&i.CreatedAt,
		&i.AcceptancePaused,
	)
	return i, err
}
