// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: linkedin_search.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLinkedInURLsForPersons = `-- name: ListLinkedInURLsForPersons :many

SELECT DISTINCT ON (pi.person_id)
    pi.person_id,
    pi.identifier_value AS linkedin_url
FROM person_identifiers pi
WHERE pi.identifier_type = 'linkedin_url'
  AND pi.person_id = ANY($1::uuid[])
ORDER BY pi.person_id
`

type ListLinkedInURLsForPersonsRow struct {
	PersonID    pgtype.UUID `json:"person_id"`
	LinkedinUrl string      `json:"linkedin_url"`
}

// Lookup query for the LinkedIn prospect source. The write-through
// itself reuses the canonical upsert queries in pdl.sql (organizations,
// persons, employments) minus the email upsert — the LinkedIn path never
// writes an emails row — and dedups on the existing FindPersonByIdentifier
// (ingest.sql) keyed on ('linkedin_url', <profile url>). This file adds
// only the result-attachment query the search handler needs.
// ListLinkedInURLsForPersons attaches the linkedin_url identifier to
// lead-search results so the UI can render a profile link. One row per
// person in the input set that carries a linkedin_url identifier.
func (q *Queries) ListLinkedInURLsForPersons(ctx context.Context, personIds []pgtype.UUID) ([]ListLinkedInURLsForPersonsRow, error) {
	rows, err := q.db.Query(ctx, listLinkedInURLsForPersons, personIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinkedInURLsForPersonsRow{}
	for rows.Next() {
		var i ListLinkedInURLsForPersonsRow
		if err := rows.Scan(&i.PersonID, &i.LinkedinUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
