// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: linkedin_events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLinkedInEvent = `-- name: CreateLinkedInEvent :one
INSERT INTO linkedin_events (campaign_lead_id, event_type, step, metadata, unipile_message_id, unipile_chat_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, campaign_lead_id, event_type, step, metadata, unipile_message_id, unipile_chat_id, created_at
`

type CreateLinkedInEventParams struct {
	CampaignLeadID   pgtype.UUID `json:"campaign_lead_id"`
	EventType        string      `json:"event_type"`
	Step             int32       `json:"step"`
	Metadata         []byte      `json:"metadata"`
	UnipileMessageID pgtype.Text `json:"unipile_message_id"`
	UnipileChatID    pgtype.Text `json:"unipile_chat_id"`
}

// One row per LinkedIn engine action against a campaign_lead. The
// LinkedIn analogue of CreateEmailEvent; unipile_message_id holds the
// invitation id on invite_sent and the message id on a DM, unipile_chat_id
// is set once a chat exists (post-acceptance, issue #5).
func (q *Queries) CreateLinkedInEvent(ctx context.Context, arg CreateLinkedInEventParams) (LinkedinEvent, error) {
	row := q.db.QueryRow(ctx, createLinkedInEvent,
		arg.CampaignLeadID,
		arg.EventType,
		arg.Step,
		arg.Metadata,
		arg.UnipileMessageID,
		arg.UnipileChatID,
	)
	var i LinkedinEvent
	err := row.Scan(
		&i.ID,
		&i.CampaignLeadID,
		&i.EventType,
		&i.Step,
		&i.Metadata,
		&i.UnipileMessageID,
		&i.UnipileChatID,
		&i.CreatedAt,
	)
	return i, err
}

const listLinkedInEvents = `-- name: ListLinkedInEvents :many
SELECT id, campaign_lead_id, event_type, step, metadata, unipile_message_id, unipile_chat_id, created_at FROM linkedin_events WHERE campaign_lead_id = $1 ORDER BY created_at
`

func (q *Queries) ListLinkedInEvents(ctx context.Context, campaignLeadID pgtype.UUID) ([]LinkedinEvent, error) {
	rows, err := q.db.Query(ctx, listLinkedInEvents, campaignLeadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkedinEvent{}
	for rows.Next() {
		var i LinkedinEvent
		if err := rows.Scan(
			&i.ID,
			&i.CampaignLeadID,
			&i.EventType,
			&i.Step,
			&i.Metadata,
			&i.UnipileMessageID,
			&i.UnipileChatID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
