// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	PlayID           pgtype.UUID        `json:"play_id"`
	Name             string             `json:"name"`
	Status           pgtype.Text        `json:"status"`
	GmailAccountID   pgtype.UUID        `json:"gmail_account_id"`
	Sequence         []byte             `json:"sequence"`
	LinkedinSequence []byte             `json:"linkedin_sequence"`
	Stats            []byte             `json:"stats"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CampaignLead struct {
	ID            pgtype.UUID        `json:"id"`
	CampaignID    pgtype.UUID        `json:"campaign_id"`
	LeadID        pgtype.UUID        `json:"lead_id"`
	Status        pgtype.Text        `json:"status"`
	CurrentStep   pgtype.Int4        `json:"current_step"`
	NextSendAt    pgtype.Timestamptz `json:"next_send_at"`
	LastSentAt    pgtype.Timestamptz `json:"last_sent_at"`
	LastOpenedAt  pgtype.Timestamptz `json:"last_opened_at"`
	LastRepliedAt pgtype.Timestamptz `json:"last_replied_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PersonID      pgtype.UUID        `json:"person_id"`
}

type ConflictQueue struct {
	ID                pgtype.UUID        `json:"id"`
	CanonicalTable    string             `json:"canonical_table"`
	CanonicalID       pgtype.UUID        `json:"canonical_id"`
	NewSourceRecordID pgtype.UUID        `json:"new_source_record_id"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type DeletionBlocklist struct {
	ID             pgtype.UUID        `json:"id"`
	IdentifierHash string             `json:"identifier_hash"`
	IdentifierType string             `json:"identifier_type"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Domain struct {
	ID             pgtype.UUID        `json:"id"`
	Domain         string             `json:"domain"`
	MxRecords      []string           `json:"mx_records"`
	IsCatchall     pgtype.Bool        `json:"is_catchall"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
}

type Email struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	PersonID           pgtype.UUID        `json:"person_id"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	VerificationMethod pgtype.Text        `json:"verification_method"`
	BounceCount        pgtype.Int4        `json:"bounce_count"`
	IsCatchall         pgtype.Bool        `json:"is_catchall"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type EmailAccount struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Provider         string             `json:"provider"`
	Email            string             `json:"email"`
	SmtpHost         pgtype.Text        `json:"smtp_host"`
	SmtpPort         pgtype.Int4        `json:"smtp_port"`
	SmtpUsername     pgtype.Text        `json:"smtp_username"`
	SmtpPassword     pgtype.Text        `json:"smtp_password"`
	AccessToken      pgtype.Text        `json:"access_token"`
	RefreshToken     pgtype.Text        `json:"refresh_token"`
	TokenExpiry      pgtype.Timestamptz `json:"token_expiry"`
	SenderName       pgtype.Text        `json:"sender_name"`
	DailySentCount   pgtype.Int4        `json:"daily_sent_count"`
	DailySentResetAt pgtype.Timestamptz `json:"daily_sent_reset_at"`
	IsActive         pgtype.Bool        `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type EmailEvent struct {
	ID             pgtype.UUID        `json:"id"`
	CampaignLeadID pgtype.UUID        `json:"campaign_lead_id"`
	EventType      string             `json:"event_type"`
	Step           int32              `json:"step"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	GmailMessageID pgtype.Text        `json:"gmail_message_id"`
}

type Employment struct {
	ID             pgtype.UUID        `json:"id"`
	PersonID       pgtype.UUID        `json:"person_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Title          pgtype.Text        `json:"title"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	IsCurrent      pgtype.Bool        `json:"is_current"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Evidence struct {
	ID               pgtype.UUID        `json:"id"`
	CanonicalTable   string             `json:"canonical_table"`
	CanonicalID      pgtype.UUID        `json:"canonical_id"`
	SourceRecordID   pgtype.UUID        `json:"source_record_id"`
	Confidence       int16              `json:"confidence"`
	ConflictFlag     pgtype.Bool        `json:"conflict_flag"`
	ResolvedByUserID pgtype.UUID        `json:"resolved_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type GmailAccount struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Email            string             `json:"email"`
	AccessToken      string             `json:"access_token"`
	RefreshToken     string             `json:"refresh_token"`
	TokenExpiry      pgtype.Timestamptz `json:"token_expiry"`
	DailySentCount   pgtype.Int4        `json:"daily_sent_count"`
	DailySentResetAt pgtype.Timestamptz `json:"daily_sent_reset_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastHistoryID    pgtype.Text        `json:"last_history_id"`
	LastPolledAt     pgtype.Timestamptz `json:"last_polled_at"`
}

type Lead struct {
	ID              pgtype.UUID        `json:"id"`
	LinkedinUrl     pgtype.Text        `json:"linkedin_url"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Title           pgtype.Text        `json:"title"`
	Company         pgtype.Text        `json:"company"`
	CompanyDomain   pgtype.Text        `json:"company_domain"`
	Location        pgtype.Text        `json:"location"`
	Email           pgtype.Text        `json:"email"`
	EmailVerified   pgtype.Bool        `json:"email_verified"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	EnrichedAt      pgtype.Timestamptz `json:"enriched_at"`
	Source          pgtype.Text        `json:"source"`
	RawData         []byte             `json:"raw_data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PersonID        pgtype.UUID        `json:"person_id"`
}

type LeadSearch struct {
	ID            pgtype.UUID        `json:"id"`
	QueryHash     string             `json:"query_hash"`
	Filters       []byte             `json:"filters"`
	ResultLeadIds []pgtype.UUID      `json:"result_lead_ids"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	TtlDays       pgtype.Int4        `json:"ttl_days"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type LinkedinTask struct {
	ID             pgtype.UUID        `json:"id"`
	CampaignLeadID pgtype.UUID        `json:"campaign_lead_id"`
	TaskType       string             `json:"task_type"`
	Payload        []byte             `json:"payload"`
	Status         pgtype.Text        `json:"status"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MergeHistory struct {
	ID             pgtype.UUID        `json:"id"`
	SurvivingID    pgtype.UUID        `json:"surviving_id"`
	MergedID       pgtype.UUID        `json:"merged_id"`
	CanonicalTable string             `json:"canonical_table"`
	MergedByUserID pgtype.UUID        `json:"merged_by_user_id"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID            pgtype.UUID        `json:"id"`
	CanonicalName string             `json:"canonical_name"`
	PrimaryDomain pgtype.Text        `json:"primary_domain"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationAlias struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Alias          string      `json:"alias"`
	AliasType      string      `json:"alias_type"`
}

type OrganizationIdentifier struct {
	ID              pgtype.UUID `json:"id"`
	OrganizationID  pgtype.UUID `json:"organization_id"`
	IdentifierType  string      `json:"identifier_type"`
	IdentifierValue string      `json:"identifier_value"`
	IsPrimary       pgtype.Bool `json:"is_primary"`
}

type Person struct {
	ID             pgtype.UUID        `json:"id"`
	CanonicalName  string             `json:"canonical_name"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	NormalizedName string             `json:"normalized_name"`
}

type PersonAlias struct {
	ID        pgtype.UUID `json:"id"`
	PersonID  pgtype.UUID `json:"person_id"`
	Alias     string      `json:"alias"`
	AliasType string      `json:"alias_type"`
}

type PersonIdentifier struct {
	ID              pgtype.UUID `json:"id"`
	PersonID        pgtype.UUID `json:"person_id"`
	IdentifierType  string      `json:"identifier_type"`
	IdentifierValue string      `json:"identifier_value"`
	IsPrimary       pgtype.Bool `json:"is_primary"`
}

type Phone struct {
	ID         pgtype.UUID        `json:"id"`
	Phone      string             `json:"phone"`
	PersonID   pgtype.UUID        `json:"person_id"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Play struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Icp         []byte             `json:"icp"`
	SearchQuery []byte             `json:"search_query"`
	Channels    []string           `json:"channels"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PrivacyRequest struct {
	ID             pgtype.UUID        `json:"id"`
	TokenHash      []byte             `json:"token_hash"`
	Email          pgtype.Text        `json:"email"`
	LinkedinUrl    pgtype.Text        `json:"linkedin_url"`
	Name           pgtype.Text        `json:"name"`
	Company        pgtype.Text        `json:"company"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	DeletedPersons pgtype.Int4        `json:"deleted_persons"`
}

type RawIngest struct {
	ID         pgtype.UUID        `json:"id"`
	SourceID   pgtype.UUID        `json:"source_id"`
	FileUrl    string             `json:"file_url"`
	IngestedAt pgtype.Timestamptz `json:"ingested_at"`
	Checksum   string             `json:"checksum"`
	SizeBytes  int64              `json:"size_bytes"`
	Meta       []byte             `json:"meta"`
}

type SocialProfile struct {
	ID        pgtype.UUID        `json:"id"`
	PersonID  pgtype.UUID        `json:"person_id"`
	Platform  string             `json:"platform"`
	Handle    pgtype.Text        `json:"handle"`
	Url       pgtype.Text        `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Source struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	ApiEndpoint    pgtype.Text        `json:"api_endpoint"`
	LastIngestedAt pgtype.Timestamptz `json:"last_ingested_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SourceRecord struct {
	ID          pgtype.UUID        `json:"id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	RawIngestID pgtype.UUID        `json:"raw_ingest_id"`
	ExternalID  pgtype.Text        `json:"external_id"`
	Fields      []byte             `json:"fields"`
	IngestedAt  pgtype.Timestamptz `json:"ingested_at"`
}

type Subscription struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	Plan                 string             `json:"plan"`
	LeadsUsed            pgtype.Int4        `json:"leads_used"`
	LeadsLimit           int32              `json:"leads_limit"`
	SequencesUsed        pgtype.Int4        `json:"sequences_used"`
	SequencesLimit       int32              `json:"sequences_limit"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Domain          string             `json:"domain"`
	BusinessProfile []byte             `json:"business_profile"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type TenantLead struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	PersonID      pgtype.UUID        `json:"person_id"`
	Status        string             `json:"status"`
	Notes         pgtype.Text        `json:"notes"`
	AddedAt       pgtype.Timestamptz `json:"added_at"`
	AddedByUserID pgtype.UUID        `json:"added_by_user_id"`
}

type Unsubscribe struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Email     string             `json:"email"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	ClerkID   string             `json:"clerk_id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserTenant struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Role      pgtype.Text        `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
