// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pdl.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizationFromPDL = `-- name: CreateOrganizationFromPDL :one
INSERT INTO organizations (canonical_name, primary_domain, industries, size_range, updated_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, canonical_name, primary_domain, created_at, updated_at, industries, size_range
`

type CreateOrganizationFromPDLParams struct {
	CanonicalName string      `json:"canonical_name"`
	PrimaryDomain pgtype.Text `json:"primary_domain"`
	Industries    []string    `json:"industries"`
	SizeRange     pgtype.Text `json:"size_range"`
}

func (q *Queries) CreateOrganizationFromPDL(ctx context.Context, arg CreateOrganizationFromPDLParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganizationFromPDL,
		arg.CanonicalName,
		arg.PrimaryDomain,
		arg.Industries,
		arg.SizeRange,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.PrimaryDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Industries,
		&i.SizeRange,
	)
	return i, err
}

const createPersonFromPDL = `-- name: CreatePersonFromPDL :one
INSERT INTO persons (canonical_name, first_name, last_name, normalized_name, location, has_email, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, canonical_name, first_name, last_name, created_at, updated_at, normalized_name, location, has_email
`

type CreatePersonFromPDLParams struct {
	CanonicalName  string      `json:"canonical_name"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	NormalizedName string      `json:"normalized_name"`
	Location       pgtype.Text `json:"location"`
	HasEmail       bool        `json:"has_email"`
}

func (q *Queries) CreatePersonFromPDL(ctx context.Context, arg CreatePersonFromPDLParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPersonFromPDL,
		arg.CanonicalName,
		arg.FirstName,
		arg.LastName,
		arg.NormalizedName,
		arg.Location,
		arg.HasEmail,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NormalizedName,
		&i.Location,
		&i.HasEmail,
	)
	return i, err
}

const findCurrentEmployment = `-- name: FindCurrentEmployment :one
SELECT id, person_id, organization_id, title, start_date, end_date, is_current, created_at FROM employments
WHERE person_id = $1 AND organization_id = $2 AND is_current = TRUE
LIMIT 1
`

type FindCurrentEmploymentParams struct {
	PersonID       pgtype.UUID `json:"person_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// FindCurrentEmployment returns the active employment (is_current=TRUE)
// between a person and an organization, regardless of title. Distinct
// from FindCurrentEmploymentByTitle in verification.sql which keys on
// title too.
func (q *Queries) FindCurrentEmployment(ctx context.Context, arg FindCurrentEmploymentParams) (Employment, error) {
	row := q.db.QueryRow(ctx, findCurrentEmployment, arg.PersonID, arg.OrganizationID)
	var i Employment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.OrganizationID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.CreatedAt,
	)
	return i, err
}

const findOrganizationByPrimaryDomain = `-- name: FindOrganizationByPrimaryDomain :one

SELECT id, canonical_name, primary_domain, created_at, updated_at, industries, size_range FROM organizations
WHERE primary_domain = $1
ORDER BY updated_at DESC NULLS LAST, created_at DESC
LIMIT 1
`

// Write-through queries for the People Data Labs integration. PDL
// search results land in the canonical graph (persons, organizations,
// employments, emails) so subsequent identical lookups across any
// tenant hit the cache for free. Stale rows (>90 days) re-trigger a
// PDL call from the handler layer.
// FindOrganizationByPrimaryDomain returns the most-recently-updated
// organization for a given domain. PDL identifies companies by domain
// as the stable join key.
func (q *Queries) FindOrganizationByPrimaryDomain(ctx context.Context, primaryDomain pgtype.Text) (Organization, error) {
	row := q.db.QueryRow(ctx, findOrganizationByPrimaryDomain, primaryDomain)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.PrimaryDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Industries,
		&i.SizeRange,
	)
	return i, err
}

const findPersonByPDLID = `-- name: FindPersonByPDLID :one
SELECT p.id, p.canonical_name, p.first_name, p.last_name, p.created_at, p.updated_at, p.normalized_name, p.location, p.has_email FROM persons p
JOIN person_identifiers pi ON pi.person_id = p.id
WHERE pi.identifier_type = 'pdl_id' AND pi.identifier_value = $1
LIMIT 1
`

// FindPersonByPDLID looks up a canonical person by the
// person_identifiers row keyed on PDL's stable person ID.
func (q *Queries) FindPersonByPDLID(ctx context.Context, identifierValue string) (Person, error) {
	row := q.db.QueryRow(ctx, findPersonByPDLID, identifierValue)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NormalizedName,
		&i.Location,
		&i.HasEmail,
	)
	return i, err
}

const updateEmploymentTitle = `-- name: UpdateEmploymentTitle :exec
UPDATE employments SET title = $2 WHERE id = $1
`

type UpdateEmploymentTitleParams struct {
	ID    pgtype.UUID `json:"id"`
	Title pgtype.Text `json:"title"`
}

func (q *Queries) UpdateEmploymentTitle(ctx context.Context, arg UpdateEmploymentTitleParams) error {
	_, err := q.db.Exec(ctx, updateEmploymentTitle, arg.ID, arg.Title)
	return err
}

const updateOrganizationFromPDL = `-- name: UpdateOrganizationFromPDL :one
UPDATE organizations
SET canonical_name = $2,
    industries     = COALESCE($3, industries),
    size_range     = COALESCE($4, size_range),
    updated_at     = NOW()
WHERE id = $1
RETURNING id, canonical_name, primary_domain, created_at, updated_at, industries, size_range
`

type UpdateOrganizationFromPDLParams struct {
	ID            pgtype.UUID `json:"id"`
	CanonicalName string      `json:"canonical_name"`
	Industries    []string    `json:"industries"`
	SizeRange     pgtype.Text `json:"size_range"`
}

func (q *Queries) UpdateOrganizationFromPDL(ctx context.Context, arg UpdateOrganizationFromPDLParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationFromPDL,
		arg.ID,
		arg.CanonicalName,
		arg.Industries,
		arg.SizeRange,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.PrimaryDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Industries,
		&i.SizeRange,
	)
	return i, err
}

const updatePersonFromPDL = `-- name: UpdatePersonFromPDL :one
UPDATE persons
SET canonical_name = $2,
    first_name      = COALESCE($3, first_name),
    last_name       = COALESCE($4, last_name),
    normalized_name = $5,
    location        = COALESCE($6, location),
    has_email       = persons.has_email OR $7,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, canonical_name, first_name, last_name, created_at, updated_at, normalized_name, location, has_email
`

type UpdatePersonFromPDLParams struct {
	ID             pgtype.UUID `json:"id"`
	CanonicalName  string      `json:"canonical_name"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	NormalizedName string      `json:"normalized_name"`
	Location       pgtype.Text `json:"location"`
	HasEmail       bool        `json:"has_email"`
}

// has_email is sticky: once a person is known emailable we never flip
// it back (a later write that happens to lack the field shouldn't lose
// the signal), so OR the existing value with the incoming one.
func (q *Queries) UpdatePersonFromPDL(ctx context.Context, arg UpdatePersonFromPDLParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePersonFromPDL,
		arg.ID,
		arg.CanonicalName,
		arg.FirstName,
		arg.LastName,
		arg.NormalizedName,
		arg.Location,
		arg.HasEmail,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.CanonicalName,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NormalizedName,
		&i.Location,
		&i.HasEmail,
	)
	return i, err
}

const upsertEmailVerifiedFromPDL = `-- name: UpsertEmailVerifiedFromPDL :one
INSERT INTO emails (email, person_id, verified_at, verification_method, updated_at)
VALUES (LOWER($1), $2, NOW(), 'pdl-verified', NOW())
ON CONFLICT (email) DO UPDATE
    SET person_id           = COALESCE(emails.person_id, EXCLUDED.person_id),
        verified_at         = NOW(),
        verification_method = 'pdl-verified',
        updated_at          = NOW()
RETURNING id, email, person_id, verified_at, verification_method, bounce_count, is_catchall, created_at, updated_at
`

type UpsertEmailVerifiedFromPDLParams struct {
	Lower    string      `json:"lower"`
	PersonID pgtype.UUID `json:"person_id"`
}

// UpsertEmailVerifiedFromPDL writes a PDL-verified email through to
// the canonical. ON CONFLICT preserves any prior person_id linkage
// (PDL's source person may differ from the canonical's, but the
// email-to-person association is stronger than transient PDL state).
func (q *Queries) UpsertEmailVerifiedFromPDL(ctx context.Context, arg UpsertEmailVerifiedFromPDLParams) (Email, error) {
	row := q.db.QueryRow(ctx, upsertEmailVerifiedFromPDL, arg.Lower, arg.PersonID)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PersonID,
		&i.VerifiedAt,
		&i.VerificationMethod,
		&i.BounceCount,
		&i.IsCatchall,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
