// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plays.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlay = `-- name: CreatePlay :one
INSERT INTO plays (tenant_id, name, description, icp, search_query, channels, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, name, description, icp, search_query, channels, status, created_at
`

type CreatePlayParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Icp         []byte      `json:"icp"`
	SearchQuery []byte      `json:"search_query"`
	Channels    []string    `json:"channels"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) CreatePlay(ctx context.Context, arg CreatePlayParams) (Play, error) {
	row := q.db.QueryRow(ctx, createPlay,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Icp,
		arg.SearchQuery,
		arg.Channels,
		arg.Status,
	)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Icp,
		&i.SearchQuery,
		&i.Channels,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlay = `-- name: DeletePlay :exec
DELETE FROM plays WHERE id = $1 AND tenant_id = $2
`

type DeletePlayParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeletePlay(ctx context.Context, arg DeletePlayParams) error {
	_, err := q.db.Exec(ctx, deletePlay, arg.ID, arg.TenantID)
	return err
}

const getPlay = `-- name: GetPlay :one
SELECT id, tenant_id, name, description, icp, search_query, channels, status, created_at FROM plays WHERE id = $1 AND tenant_id = $2
`

type GetPlayParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPlay(ctx context.Context, arg GetPlayParams) (Play, error) {
	row := q.db.QueryRow(ctx, getPlay, arg.ID, arg.TenantID)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Icp,
		&i.SearchQuery,
		&i.Channels,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPlays = `-- name: ListPlays :many
SELECT id, tenant_id, name, description, icp, search_query, channels, status, created_at FROM plays WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPlays(ctx context.Context, tenantID pgtype.UUID) ([]Play, error) {
	rows, err := q.db.Query(ctx, listPlays, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Play{}
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Icp,
			&i.SearchQuery,
			&i.Channels,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlay = `-- name: UpdatePlay :one
UPDATE plays SET name = $2, description = $3, icp = $4, search_query = $5, channels = $6, status = $7
WHERE id = $1 RETURNING id, tenant_id, name, description, icp, search_query, channels, status, created_at
`

type UpdatePlayParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Icp         []byte      `json:"icp"`
	SearchQuery []byte      `json:"search_query"`
	Channels    []string    `json:"channels"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) UpdatePlay(ctx context.Context, arg UpdatePlayParams) (Play, error) {
	row := q.db.QueryRow(ctx, updatePlay,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icp,
		arg.SearchQuery,
		arg.Channels,
		arg.Status,
	)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Icp,
		&i.SearchQuery,
		&i.Channels,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
