// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: privacy_requests.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPrivacyRequest = `-- name: ConfirmPrivacyRequest :exec
UPDATE privacy_requests
SET confirmed_at = NOW(), deleted_persons = $2
WHERE id = $1
`

type ConfirmPrivacyRequestParams struct {
	ID             pgtype.UUID `json:"id"`
	DeletedPersons pgtype.Int4 `json:"deleted_persons"`
}

func (q *Queries) ConfirmPrivacyRequest(ctx context.Context, arg ConfirmPrivacyRequestParams) error {
	_, err := q.db.Exec(ctx, confirmPrivacyRequest, arg.ID, arg.DeletedPersons)
	return err
}

const getPrivacyRequestByTokenHash = `-- name: GetPrivacyRequestByTokenHash :one
SELECT id, token_hash, email, linkedin_url, name, company, reason, created_at, expires_at, confirmed_at, deleted_persons FROM privacy_requests WHERE token_hash = $1
`

func (q *Queries) GetPrivacyRequestByTokenHash(ctx context.Context, tokenHash []byte) (PrivacyRequest, error) {
	row := q.db.QueryRow(ctx, getPrivacyRequestByTokenHash, tokenHash)
	var i PrivacyRequest
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.LinkedinUrl,
		&i.Name,
		&i.Company,
		&i.Reason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.DeletedPersons,
	)
	return i, err
}

const insertPrivacyRequest = `-- name: InsertPrivacyRequest :one

INSERT INTO privacy_requests (
    token_hash, email, linkedin_url, name, company, reason, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, token_hash, email, linkedin_url, name, company, reason, created_at, expires_at, confirmed_at, deleted_persons
`

type InsertPrivacyRequestParams struct {
	TokenHash   []byte             `json:"token_hash"`
	Email       pgtype.Text        `json:"email"`
	LinkedinUrl pgtype.Text        `json:"linkedin_url"`
	Name        pgtype.Text        `json:"name"`
	Company     pgtype.Text        `json:"company"`
	Reason      pgtype.Text        `json:"reason"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Pending erasure requests awaiting confirmation. Plan §T15.
func (q *Queries) InsertPrivacyRequest(ctx context.Context, arg InsertPrivacyRequestParams) (PrivacyRequest, error) {
	row := q.db.QueryRow(ctx, insertPrivacyRequest,
		arg.TokenHash,
		arg.Email,
		arg.LinkedinUrl,
		arg.Name,
		arg.Company,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i PrivacyRequest
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.LinkedinUrl,
		&i.Name,
		&i.Company,
		&i.Reason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.DeletedPersons,
	)
	return i, err
}
