// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: privacy.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anyHashBlocked = `-- name: AnyHashBlocked :one
SELECT EXISTS(
    SELECT 1 FROM deletion_blocklist
    WHERE identifier_hash = ANY($1::text[])
) AS blocked
`

// AnyHashBlocked is the resolver's gate before creating a new
// canonical person — pass every identifier hash the source record
// yields, get back a single bool. Hashes are SHA-256 hex; collisions
// are negligible so we don't filter by identifier_type here.
func (q *Queries) AnyHashBlocked(ctx context.Context, hashes []string) (bool, error) {
	row := q.db.QueryRow(ctx, anyHashBlocked, hashes)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const findPersonIDsByEmail = `-- name: FindPersonIDsByEmail :many

SELECT DISTINCT person_id FROM emails
WHERE LOWER(email) = LOWER($1)
  AND person_id IS NOT NULL
`

// Privacy / right-to-erasure queries (plan §T16).
//
// These power POST /api/v1/privacy/erasure: identify the canonical
// person(s) matching the requester's identifiers, hard-delete them
// (CASCADE clears employments / emails / aliases / etc.), and write
// hashed identifier rows to deletion_blocklist so the resolver can
// refuse to re-create the record from a future ingest.
// FindPersonIDsByEmail returns person IDs for any verified or
// unverified email matching the input. Email matching is
// case-insensitive (LOWER on both sides). NULL person_id rows are
// excluded — those represent unattached emails.
func (q *Queries) FindPersonIDsByEmail(ctx context.Context, lower string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, findPersonIDsByEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var person_id pgtype.UUID
		if err := rows.Scan(&person_id); err != nil {
			return nil, err
		}
		items = append(items, person_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPersonIDsByLinkedIn = `-- name: FindPersonIDsByLinkedIn :many
SELECT DISTINCT person_id FROM person_identifiers
WHERE identifier_type = 'linkedin' AND identifier_value = $1
`

// FindPersonIDsByLinkedIn returns person IDs whose person_identifiers
// carries the given normalized LinkedIn URL. Caller is responsible
// for normalization (see ingest/resolver.go normalizeLinkedInURL).
func (q *Queries) FindPersonIDsByLinkedIn(ctx context.Context, identifierValue string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, findPersonIDsByLinkedIn, identifierValue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var person_id pgtype.UUID
		if err := rows.Scan(&person_id); err != nil {
			return nil, err
		}
		items = append(items, person_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPersonIDsByNormalizedNameAndOrg = `-- name: FindPersonIDsByNormalizedNameAndOrg :many
SELECT DISTINCT p.id FROM persons p
JOIN employments e ON e.person_id = p.id
JOIN organizations o ON o.id = e.organization_id
WHERE p.normalized_name = $1::text
  AND (
    o.canonical_name ILIKE '%' || $2::text || '%'
    OR $2::text ILIKE '%' || o.canonical_name || '%'
    OR EXISTS (
        SELECT 1 FROM organization_aliases oa
        WHERE oa.organization_id = o.id
          AND (oa.alias ILIKE '%' || $2::text || '%'
               OR $2::text ILIKE '%' || oa.alias || '%')
    )
  )
`

type FindPersonIDsByNormalizedNameAndOrgParams struct {
	NormalizedName string `json:"normalized_name"`
	Company        string `json:"company"`
}

// FindPersonIDsByNormalizedNameAndOrg matches the person's normalized
// name (alphabetically-sorted lowercase tokens, see resolver.go
// normalizeName) against an org's canonical_name or any alias. ILIKE
// with bidirectional substring lets "Apple" match "Apple Inc" without
// requiring a normalized_canonical_name column on organizations.
func (q *Queries) FindPersonIDsByNormalizedNameAndOrg(ctx context.Context, arg FindPersonIDsByNormalizedNameAndOrgParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, findPersonIDsByNormalizedNameAndOrg, arg.NormalizedName, arg.Company)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBlocklistEntry = `-- name: InsertBlocklistEntry :exec
INSERT INTO deletion_blocklist (identifier_type, identifier_hash, reason)
VALUES ($1, $2, $3)
ON CONFLICT (identifier_type, identifier_hash) DO NOTHING
`

type InsertBlocklistEntryParams struct {
	IdentifierType string      `json:"identifier_type"`
	IdentifierHash string      `json:"identifier_hash"`
	Reason         pgtype.Text `json:"reason"`
}

// InsertBlocklistEntry is idempotent: re-erasing the same identifier
// doesn't error.
func (q *Queries) InsertBlocklistEntry(ctx context.Context, arg InsertBlocklistEntryParams) error {
	_, err := q.db.Exec(ctx, insertBlocklistEntry, arg.IdentifierType, arg.IdentifierHash, arg.Reason)
	return err
}
