// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (tenant_id, plan, leads_limit, sequences_limit, stripe_customer_id, stripe_subscription_id, current_period_start, current_period_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, plan, leads_used, leads_limit, sequences_used, sequences_limit, current_period_start, current_period_end, stripe_customer_id, stripe_subscription_id, created_at
`

type CreateSubscriptionParams struct {
	TenantID             pgtype.UUID        `json:"tenant_id"`
	Plan                 string             `json:"plan"`
	LeadsLimit           int32              `json:"leads_limit"`
	SequencesLimit       int32              `json:"sequences_limit"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.TenantID,
		arg.Plan,
		arg.LeadsLimit,
		arg.SequencesLimit,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Plan,
		&i.LeadsUsed,
		&i.LeadsLimit,
		&i.SequencesUsed,
		&i.SequencesLimit,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
	)
	return i, err
}

const downgradeByStripeSubscriptionID = `-- name: DowngradeByStripeSubscriptionID :exec
UPDATE subscriptions
SET plan = $2, leads_limit = $3, sequences_limit = $4,
    stripe_subscription_id = NULL,
    current_period_start = NULL,
    current_period_end = NULL
WHERE stripe_subscription_id = $1
`

type DowngradeByStripeSubscriptionIDParams struct {
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
	Plan                 string      `json:"plan"`
	LeadsLimit           int32       `json:"leads_limit"`
	SequencesLimit       int32       `json:"sequences_limit"`
}

// DowngradeByStripeSubscriptionID finds the subscription linked to a
// Stripe subscription ID and resets it to the given plan/limits.
// Used by the customer.subscription.deleted webhook to flip a tenant
// back to free without needing to know their tenant_id.
func (q *Queries) DowngradeByStripeSubscriptionID(ctx context.Context, arg DowngradeByStripeSubscriptionIDParams) error {
	_, err := q.db.Exec(ctx, downgradeByStripeSubscriptionID,
		arg.StripeSubscriptionID,
		arg.Plan,
		arg.LeadsLimit,
		arg.SequencesLimit,
	)
	return err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, tenant_id, plan, leads_used, leads_limit, sequences_used, sequences_limit, current_period_start, current_period_end, stripe_customer_id, stripe_subscription_id, created_at FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, tenantID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, tenantID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Plan,
		&i.LeadsUsed,
		&i.LeadsLimit,
		&i.SequencesUsed,
		&i.SequencesLimit,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
	)
	return i, err
}

const incrementLeadsUsed = `-- name: IncrementLeadsUsed :exec
UPDATE subscriptions SET leads_used = leads_used + $2 WHERE tenant_id = $1
`

type IncrementLeadsUsedParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	LeadsUsed pgtype.Int4 `json:"leads_used"`
}

func (q *Queries) IncrementLeadsUsed(ctx context.Context, arg IncrementLeadsUsedParams) error {
	_, err := q.db.Exec(ctx, incrementLeadsUsed, arg.TenantID, arg.LeadsUsed)
	return err
}

const incrementSequencesUsed = `-- name: IncrementSequencesUsed :exec
UPDATE subscriptions SET sequences_used = sequences_used + $2 WHERE tenant_id = $1
`

type IncrementSequencesUsedParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	SequencesUsed pgtype.Int4 `json:"sequences_used"`
}

func (q *Queries) IncrementSequencesUsed(ctx context.Context, arg IncrementSequencesUsedParams) error {
	_, err := q.db.Exec(ctx, incrementSequencesUsed, arg.TenantID, arg.SequencesUsed)
	return err
}

const resetUsageCounts = `-- name: ResetUsageCounts :exec
UPDATE subscriptions SET leads_used = 0, sequences_used = 0
WHERE current_period_end < NOW()
`

func (q *Queries) ResetUsageCounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetUsageCounts)
	return err
}

const updateStripeCustomer = `-- name: UpdateStripeCustomer :exec
UPDATE subscriptions SET stripe_customer_id = $2 WHERE tenant_id = $1
`

type UpdateStripeCustomerParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
}

func (q *Queries) UpdateStripeCustomer(ctx context.Context, arg UpdateStripeCustomerParams) error {
	_, err := q.db.Exec(ctx, updateStripeCustomer, arg.TenantID, arg.StripeCustomerID)
	return err
}

const updateSubscriptionByStripeID = `-- name: UpdateSubscriptionByStripeID :exec
UPDATE subscriptions
SET plan = $2, leads_limit = $3, sequences_limit = $4,
    current_period_start = $5,
    current_period_end = $6
WHERE stripe_subscription_id = $1
`

type UpdateSubscriptionByStripeIDParams struct {
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	Plan                 string             `json:"plan"`
	LeadsLimit           int32              `json:"leads_limit"`
	SequencesLimit       int32              `json:"sequences_limit"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
}

// UpdateSubscriptionByStripeID is called from customer.subscription.{created,updated}.
// The webhook payload identifies the subscription by Stripe ID, not
// tenant_id, so we match on stripe_subscription_id. Period dates flow
// through unchanged from Stripe.
func (q *Queries) UpdateSubscriptionByStripeID(ctx context.Context, arg UpdateSubscriptionByStripeIDParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionByStripeID,
		arg.StripeSubscriptionID,
		arg.Plan,
		arg.LeadsLimit,
		arg.SequencesLimit,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	return err
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :exec
UPDATE subscriptions SET plan = $2, leads_limit = $3, sequences_limit = $4, stripe_subscription_id = $5, current_period_start = $6, current_period_end = $7
WHERE tenant_id = $1
`

type UpdateSubscriptionPlanParams struct {
	TenantID             pgtype.UUID        `json:"tenant_id"`
	Plan                 string             `json:"plan"`
	LeadsLimit           int32              `json:"leads_limit"`
	SequencesLimit       int32              `json:"sequences_limit"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionPlan,
		arg.TenantID,
		arg.Plan,
		arg.LeadsLimit,
		arg.SequencesLimit,
		arg.StripeSubscriptionID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	return err
}
