// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppression.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearReplyUnsubscribe = `-- name: ClearReplyUnsubscribe :exec
DELETE FROM unsubscribes
WHERE tenant_id = $1
  AND lower(email) = lower($2::text)
  AND reason = 'reply'
`

type ClearReplyUnsubscribeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// ClearReplyUnsubscribe deletes the reply-reason suppression row for
// (tenant, email). Used by the re-engage handler when the operator
// decides a reply was actually an auto-responder (out-of-office,
// vacation-reply) and wants the sequence to resume. Other reasons
// (manual / list-unsub / spam-complaint / hard-bounce / soft-bounce-
// threshold) are deliberately NOT touched — only the reply gate is
// recoverable; the others are permanent for safety / compliance.
func (q *Queries) ClearReplyUnsubscribe(ctx context.Context, arg ClearReplyUnsubscribeParams) error {
	_, err := q.db.Exec(ctx, clearReplyUnsubscribe, arg.TenantID, arg.Email)
	return err
}

const countConsecutiveSoftBounces = `-- name: CountConsecutiveSoftBounces :one
WITH cl_match AS (
    SELECT cl.id
    FROM campaign_leads cl
    JOIN campaigns c    ON c.id = cl.campaign_id
    LEFT JOIN persons p ON p.id = cl.person_id
    LEFT JOIN emails em ON em.person_id = p.id
    LEFT JOIN leads l   ON l.id = cl.lead_id
    WHERE c.tenant_id = $1
      AND (lower(em.email) = lower($2::text) OR lower(l.email) = lower($2::text))
),
last_sent AS (
    SELECT COALESCE(max(created_at), '1970-01-01'::timestamptz) AS at
    FROM email_events
    WHERE campaign_lead_id IN (SELECT id FROM cl_match)
      AND event_type = 'sent'
)
SELECT COUNT(*)::bigint
FROM email_events
WHERE campaign_lead_id IN (SELECT id FROM cl_match)
  AND event_type = 'soft-bounce'
  AND created_at > (SELECT at FROM last_sent)
`

type CountConsecutiveSoftBouncesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// Returns the count of 'soft-bounce' email_events since the last
// successful 'sent' event for any campaign_lead in this tenant that
// resolves to this email. "Consecutive" = no successful send has
// reset the streak.
func (q *Queries) CountConsecutiveSoftBounces(ctx context.Context, arg CountConsecutiveSoftBouncesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConsecutiveSoftBounces, arg.TenantID, arg.Email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findCampaignLeadForEmail = `-- name: FindCampaignLeadForEmail :one
SELECT cl.id
FROM campaign_leads cl
JOIN campaigns c    ON c.id = cl.campaign_id
LEFT JOIN persons p ON p.id = cl.person_id
LEFT JOIN emails em ON em.person_id = p.id
LEFT JOIN leads l   ON l.id = cl.lead_id
WHERE c.tenant_id = $1
  AND (lower(em.email) = lower($2::text) OR lower(l.email) = lower($2::text))
ORDER BY cl.created_at DESC
LIMIT 1
`

type FindCampaignLeadForEmailParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// Returns the most-recently-created campaign_lead in this tenant that
// resolves to this email. Used by bounce recorders that take only
// (email, tenant) and need a campaign_lead_id to anchor the event row.
func (q *Queries) FindCampaignLeadForEmail(ctx context.Context, arg FindCampaignLeadForEmailParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findCampaignLeadForEmail, arg.TenantID, arg.Email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const hasHardBounceEvent = `-- name: HasHardBounceEvent :one
SELECT EXISTS (
    SELECT 1
    FROM email_events ee
    JOIN campaign_leads cl ON cl.id = ee.campaign_lead_id
    JOIN campaigns c       ON c.id  = cl.campaign_id
    LEFT JOIN persons p    ON p.id  = cl.person_id
    LEFT JOIN emails em    ON em.person_id = p.id
    LEFT JOIN leads l      ON l.id  = cl.lead_id
    WHERE c.tenant_id = $1
      AND ee.event_type = 'bounced'
      AND (lower(em.email) = lower($2::text) OR lower(l.email) = lower($2::text))
)
`

type HasHardBounceEventParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// True if any campaign_lead for this tenant that resolves to this
// email has a 'bounced' email_event row.
func (q *Queries) HasHardBounceEvent(ctx context.Context, arg HasHardBounceEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasHardBounceEvent, arg.TenantID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertUnsubscribeGlobal = `-- name: InsertUnsubscribeGlobal :exec
INSERT INTO unsubscribes (tenant_id, email, reason)
VALUES (NULL, $1::text, $2)
ON CONFLICT (COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(email)) DO NOTHING
`

type InsertUnsubscribeGlobalParams struct {
	Email  string `json:"email"`
	Reason string `json:"reason"`
}

// Idempotent insert of a global (tenant_id = NULL) suppression row.
func (q *Queries) InsertUnsubscribeGlobal(ctx context.Context, arg InsertUnsubscribeGlobalParams) error {
	_, err := q.db.Exec(ctx, insertUnsubscribeGlobal, arg.Email, arg.Reason)
	return err
}

const insertUnsubscribePerson = `-- name: InsertUnsubscribePerson :exec
INSERT INTO unsubscribes (tenant_id, person_id, reason)
VALUES ($1, $2, $3)
ON CONFLICT (COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), person_id)
    WHERE person_id IS NOT NULL
    DO NOTHING
`

type InsertUnsubscribePersonParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PersonID pgtype.UUID `json:"person_id"`
	Reason   string      `json:"reason"`
}

// Idempotent insert of a person-keyed suppression row (the LinkedIn rail —
// prospects have no email). The partial-index predicate on the conflict
// target tells Postgres which arbiter index to use.
func (q *Queries) InsertUnsubscribePerson(ctx context.Context, arg InsertUnsubscribePersonParams) error {
	_, err := q.db.Exec(ctx, insertUnsubscribePerson, arg.TenantID, arg.PersonID, arg.Reason)
	return err
}

const insertUnsubscribeTenant = `-- name: InsertUnsubscribeTenant :exec
INSERT INTO unsubscribes (tenant_id, email, reason)
VALUES ($1, $2::text, $3)
ON CONFLICT (COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(email)) DO NOTHING
`

type InsertUnsubscribeTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
	Reason   string      `json:"reason"`
}

// Idempotent insert of a tenant-scoped suppression row. The ::text cast
// pins the email param to a non-null string even though the column is now
// nullable (person rows carry no email) — keeps the email write path's Go
// API unchanged.
func (q *Queries) InsertUnsubscribeTenant(ctx context.Context, arg InsertUnsubscribeTenantParams) error {
	_, err := q.db.Exec(ctx, insertUnsubscribeTenant, arg.TenantID, arg.Email, arg.Reason)
	return err
}

const listUnsubscribesForTenant = `-- name: ListUnsubscribesForTenant :many
SELECT id, tenant_id, email, reason, created_at, person_id FROM unsubscribes
WHERE tenant_id = $1
ORDER BY created_at
`

// ListUnsubscribesForTenant dumps every tenant-scoped unsubscribe row
// (excludes globals where tenant_id IS NULL). Used by the GDPR
// account-export endpoint (issue #11) to write unsubscribes.json.
func (q *Queries) ListUnsubscribesForTenant(ctx context.Context, tenantID pgtype.UUID) ([]Unsubscribe, error) {
	rows, err := q.db.Query(ctx, listUnsubscribesForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unsubscribe{}
	for rows.Next() {
		var i Unsubscribe
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Reason,
			&i.CreatedAt,
			&i.PersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupSuppression = `-- name: LookupSuppression :one

SELECT reason
FROM unsubscribes
WHERE (tenant_id = $1 OR tenant_id IS NULL)
  AND lower(email) = lower($2::text)
ORDER BY (tenant_id IS NULL) ASC
LIMIT 1
`

type LookupSuppressionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// Queries that back the suppression deep module
// (backend/internal/suppression). IsSuppressed reads from three
// sources: the unsubscribes table (tenant-specific or global), and
// email_events bounce signals reachable from campaign_leads that
// resolve to the candidate email.
//
// Email resolution joins through campaign_leads → (persons + emails)
// or → leads (legacy), case-insensitive, so the suppression module
// doesn't care which ingest path populated the address.
// Returns the suppression reason if (tenant_id, email) is suppressed,
// prefering a tenant-specific row over a global one.
func (q *Queries) LookupSuppression(ctx context.Context, arg LookupSuppressionParams) (string, error) {
	row := q.db.QueryRow(ctx, lookupSuppression, arg.TenantID, arg.Email)
	var reason string
	err := row.Scan(&reason)
	return reason, err
}

const lookupSuppressionByPerson = `-- name: LookupSuppressionByPerson :one
SELECT reason
FROM unsubscribes
WHERE (tenant_id = $1 OR tenant_id IS NULL)
  AND person_id = $2
ORDER BY (tenant_id IS NULL) ASC
LIMIT 1
`

type LookupSuppressionByPersonParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PersonID pgtype.UUID `json:"person_id"`
}

// Person-keyed analogue of LookupSuppression: returns the suppression
// reason if (tenant_id, person_id) is suppressed, preferring a tenant row
// over a global one. No bounce layers — LinkedIn has no bounces.
func (q *Queries) LookupSuppressionByPerson(ctx context.Context, arg LookupSuppressionByPersonParams) (string, error) {
	row := q.db.QueryRow(ctx, lookupSuppressionByPerson, arg.TenantID, arg.PersonID)
	var reason string
	err := row.Scan(&reason)
	return reason, err
}

const markCampaignLeadReplied = `-- name: MarkCampaignLeadReplied :exec
UPDATE campaign_leads
SET status = 'replied', last_replied_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkCampaignLeadReplied(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCampaignLeadReplied, id)
	return err
}

const markLinkedInLeadReplied = `-- name: MarkLinkedInLeadReplied :one
UPDATE campaign_leads
SET status = 'replied', last_replied_at = NOW()
WHERE id = $1 AND status <> 'replied'
RETURNING id
`

// Idempotency gate for the LinkedIn reply path: flip the lead to 'replied'
// only if it is not already, RETURNING its id. A replay (duplicate webhook,
// or webhook + reconcile overlap) updates zero rows and yields no row, so
// the caller writes no duplicate event or suppression. Flips from any
// non-replied state (active / awaiting_accept / exhausted) so a late reply
// still suppresses the person.
func (q *Queries) MarkLinkedInLeadReplied(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markLinkedInLeadReplied, id)
	err := row.Scan(&id)
	return id, err
}

const reactivateCampaignLead = `-- name: ReactivateCampaignLead :exec
UPDATE campaign_leads
SET status = 'active', next_send_at = NOW(), last_replied_at = NULL
WHERE id = $1
`

// ReactivateCampaignLead is the second half of the re-engage flow:
// after ClearReplyUnsubscribe lifts the suppression, this flips the
// lead back to 'active' and arms next_send_at so the worker picks it
// up on the next tick. Step is left unchanged — the sequence
// continues from where it was when the reply landed.
func (q *Queries) ReactivateCampaignLead(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reactivateCampaignLead, id)
	return err
}

const resolveCampaignLeadAddress = `-- name: ResolveCampaignLeadAddress :one
WITH best AS (
    SELECT DISTINCT ON (em.person_id) em.person_id, em.email
    FROM emails em
    ORDER BY em.person_id,
             (em.verified_at IS NOT NULL) DESC,
             em.bounce_count ASC,
             em.created_at ASC
)
SELECT
    c.tenant_id,
    COALESCE(b.email, l.email, '')::text AS email
FROM campaign_leads cl
JOIN campaigns c       ON c.id = cl.campaign_id
LEFT JOIN persons p    ON p.id = cl.person_id
LEFT JOIN best b       ON b.person_id = p.id
LEFT JOIN leads l      ON l.id = cl.lead_id
WHERE cl.id = $1
`

type ResolveCampaignLeadAddressRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// Returns (tenant_id, email) for a given campaign_lead, using the same
// canonical/legacy resolution as GetDueLeads.
func (q *Queries) ResolveCampaignLeadAddress(ctx context.Context, id pgtype.UUID) (ResolveCampaignLeadAddressRow, error) {
	row := q.db.QueryRow(ctx, resolveCampaignLeadAddress, id)
	var i ResolveCampaignLeadAddressRow
	err := row.Scan(&i.TenantID, &i.Email)
	return i, err
}

const resolveCampaignLeadPerson = `-- name: ResolveCampaignLeadPerson :one
SELECT c.tenant_id, cl.person_id
FROM campaign_leads cl
JOIN campaigns c ON c.id = cl.campaign_id
WHERE cl.id = $1
`

type ResolveCampaignLeadPersonRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PersonID pgtype.UUID `json:"person_id"`
}

// Returns (tenant_id, person_id) for a campaign_lead — the person analogue
// of ResolveCampaignLeadAddress, used by the LinkedIn reply path to key the
// person-scoped suppression row.
func (q *Queries) ResolveCampaignLeadPerson(ctx context.Context, id pgtype.UUID) (ResolveCampaignLeadPersonRow, error) {
	row := q.db.QueryRow(ctx, resolveCampaignLeadPerson, id)
	var i ResolveCampaignLeadPersonRow
	err := row.Scan(&i.TenantID, &i.PersonID)
	return i, err
}
