// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppression.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConsecutiveSoftBounces = `-- name: CountConsecutiveSoftBounces :one
WITH cl_match AS (
    SELECT cl.id
    FROM campaign_leads cl
    JOIN campaigns c    ON c.id = cl.campaign_id
    LEFT JOIN persons p ON p.id = cl.person_id
    LEFT JOIN emails em ON em.person_id = p.id
    LEFT JOIN leads l   ON l.id = cl.lead_id
    WHERE c.tenant_id = $1
      AND (lower(em.email) = lower($2::text) OR lower(l.email) = lower($2::text))
),
last_sent AS (
    SELECT COALESCE(max(created_at), '1970-01-01'::timestamptz) AS at
    FROM email_events
    WHERE campaign_lead_id IN (SELECT id FROM cl_match)
      AND event_type = 'sent'
)
SELECT COUNT(*)::bigint
FROM email_events
WHERE campaign_lead_id IN (SELECT id FROM cl_match)
  AND event_type = 'soft-bounce'
  AND created_at > (SELECT at FROM last_sent)
`

type CountConsecutiveSoftBouncesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// Returns the count of 'soft-bounce' email_events since the last
// successful 'sent' event for any campaign_lead in this tenant that
// resolves to this email. "Consecutive" = no successful send has
// reset the streak.
func (q *Queries) CountConsecutiveSoftBounces(ctx context.Context, arg CountConsecutiveSoftBouncesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConsecutiveSoftBounces, arg.TenantID, arg.Email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findCampaignLeadForEmail = `-- name: FindCampaignLeadForEmail :one
SELECT cl.id
FROM campaign_leads cl
JOIN campaigns c    ON c.id = cl.campaign_id
LEFT JOIN persons p ON p.id = cl.person_id
LEFT JOIN emails em ON em.person_id = p.id
LEFT JOIN leads l   ON l.id = cl.lead_id
WHERE c.tenant_id = $1
  AND (lower(em.email) = lower($2::text) OR lower(l.email) = lower($2::text))
ORDER BY cl.created_at DESC
LIMIT 1
`

type FindCampaignLeadForEmailParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// Returns the most-recently-created campaign_lead in this tenant that
// resolves to this email. Used by bounce recorders that take only
// (email, tenant) and need a campaign_lead_id to anchor the event row.
func (q *Queries) FindCampaignLeadForEmail(ctx context.Context, arg FindCampaignLeadForEmailParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findCampaignLeadForEmail, arg.TenantID, arg.Email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const hasHardBounceEvent = `-- name: HasHardBounceEvent :one
SELECT EXISTS (
    SELECT 1
    FROM email_events ee
    JOIN campaign_leads cl ON cl.id = ee.campaign_lead_id
    JOIN campaigns c       ON c.id  = cl.campaign_id
    LEFT JOIN persons p    ON p.id  = cl.person_id
    LEFT JOIN emails em    ON em.person_id = p.id
    LEFT JOIN leads l      ON l.id  = cl.lead_id
    WHERE c.tenant_id = $1
      AND ee.event_type = 'bounced'
      AND (lower(em.email) = lower($2::text) OR lower(l.email) = lower($2::text))
)
`

type HasHardBounceEventParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// True if any campaign_lead for this tenant that resolves to this
// email has a 'bounced' email_event row.
func (q *Queries) HasHardBounceEvent(ctx context.Context, arg HasHardBounceEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasHardBounceEvent, arg.TenantID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertUnsubscribeGlobal = `-- name: InsertUnsubscribeGlobal :exec
INSERT INTO unsubscribes (tenant_id, email, reason)
VALUES (NULL, $1, $2)
ON CONFLICT (COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(email)) DO NOTHING
`

type InsertUnsubscribeGlobalParams struct {
	Email  string `json:"email"`
	Reason string `json:"reason"`
}

// Idempotent insert of a global (tenant_id = NULL) suppression row.
func (q *Queries) InsertUnsubscribeGlobal(ctx context.Context, arg InsertUnsubscribeGlobalParams) error {
	_, err := q.db.Exec(ctx, insertUnsubscribeGlobal, arg.Email, arg.Reason)
	return err
}

const insertUnsubscribeTenant = `-- name: InsertUnsubscribeTenant :exec
INSERT INTO unsubscribes (tenant_id, email, reason)
VALUES ($1, $2, $3)
ON CONFLICT (COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(email)) DO NOTHING
`

type InsertUnsubscribeTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
	Reason   string      `json:"reason"`
}

// Idempotent insert of a tenant-scoped suppression row.
func (q *Queries) InsertUnsubscribeTenant(ctx context.Context, arg InsertUnsubscribeTenantParams) error {
	_, err := q.db.Exec(ctx, insertUnsubscribeTenant, arg.TenantID, arg.Email, arg.Reason)
	return err
}

const lookupSuppression = `-- name: LookupSuppression :one

SELECT reason
FROM unsubscribes
WHERE (tenant_id = $1 OR tenant_id IS NULL)
  AND lower(email) = lower($2::text)
ORDER BY (tenant_id IS NULL) ASC
LIMIT 1
`

type LookupSuppressionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// Queries that back the suppression deep module
// (backend/internal/suppression). IsSuppressed reads from three
// sources: the unsubscribes table (tenant-specific or global), and
// email_events bounce signals reachable from campaign_leads that
// resolve to the candidate email.
//
// Email resolution joins through campaign_leads → (persons + emails)
// or → leads (legacy), case-insensitive, so the suppression module
// doesn't care which ingest path populated the address.
// Returns the suppression reason if (tenant_id, email) is suppressed,
// prefering a tenant-specific row over a global one.
func (q *Queries) LookupSuppression(ctx context.Context, arg LookupSuppressionParams) (string, error) {
	row := q.db.QueryRow(ctx, lookupSuppression, arg.TenantID, arg.Email)
	var reason string
	err := row.Scan(&reason)
	return reason, err
}

const markCampaignLeadReplied = `-- name: MarkCampaignLeadReplied :exec
UPDATE campaign_leads
SET status = 'replied', last_replied_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkCampaignLeadReplied(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCampaignLeadReplied, id)
	return err
}

const resolveCampaignLeadAddress = `-- name: ResolveCampaignLeadAddress :one
WITH best AS (
    SELECT DISTINCT ON (em.person_id) em.person_id, em.email
    FROM emails em
    ORDER BY em.person_id,
             (em.verified_at IS NOT NULL) DESC,
             em.bounce_count ASC,
             em.created_at ASC
)
SELECT
    c.tenant_id,
    COALESCE(b.email, l.email, '')::text AS email
FROM campaign_leads cl
JOIN campaigns c       ON c.id = cl.campaign_id
LEFT JOIN persons p    ON p.id = cl.person_id
LEFT JOIN best b       ON b.person_id = p.id
LEFT JOIN leads l      ON l.id = cl.lead_id
WHERE cl.id = $1
`

type ResolveCampaignLeadAddressRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

// Returns (tenant_id, email) for a given campaign_lead, using the same
// canonical/legacy resolution as GetDueLeads.
func (q *Queries) ResolveCampaignLeadAddress(ctx context.Context, id pgtype.UUID) (ResolveCampaignLeadAddressRow, error) {
	row := q.db.QueryRow(ctx, resolveCampaignLeadAddress, id)
	var i ResolveCampaignLeadAddressRow
	err := row.Scan(&i.TenantID, &i.Email)
	return i, err
}
