// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenants.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, domain, business_profile) VALUES ($1, $2, $3) RETURNING id, name, domain, business_profile, created_at, updated_at
`

type CreateTenantParams struct {
	Name            string `json:"name"`
	Domain          string `json:"domain"`
	BusinessProfile []byte `json:"business_profile"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Domain, arg.BusinessProfile)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.BusinessProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserTenant = `-- name: CreateUserTenant :exec
INSERT INTO user_tenants (user_id, tenant_id, role) VALUES ($1, $2, $3)
`

type CreateUserTenantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Role     pgtype.Text `json:"role"`
}

func (q *Queries) CreateUserTenant(ctx context.Context, arg CreateUserTenantParams) error {
	_, err := q.db.Exec(ctx, createUserTenant, arg.UserID, arg.TenantID, arg.Role)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, domain, business_profile, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.BusinessProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantsByUser = `-- name: ListTenantsByUser :many
SELECT t.id, t.name, t.domain, t.business_profile, t.created_at, t.updated_at FROM tenants t
JOIN user_tenants ut ON t.id = ut.tenant_id
WHERE ut.user_id = $1
`

func (q *Queries) ListTenantsByUser(ctx context.Context, userID pgtype.UUID) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.BusinessProfile,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantProfile = `-- name: UpdateTenantProfile :one
UPDATE tenants SET business_profile = $2, updated_at = NOW() WHERE id = $1 RETURNING id, name, domain, business_profile, created_at, updated_at
`

type UpdateTenantProfileParams struct {
	ID              pgtype.UUID `json:"id"`
	BusinessProfile []byte      `json:"business_profile"`
}

func (q *Queries) UpdateTenantProfile(ctx context.Context, arg UpdateTenantProfileParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantProfile, arg.ID, arg.BusinessProfile)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.BusinessProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
