// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenant_leads.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTenantLead = `-- name: AddTenantLead :one

INSERT INTO tenant_leads (tenant_id, person_id, status, notes, added_by_user_id)
VALUES ($1, $2, COALESCE($5::text, 'new'), $3, $4)
ON CONFLICT (tenant_id, person_id) DO UPDATE
    SET status           = COALESCE(EXCLUDED.status, tenant_leads.status),
        notes            = COALESCE(EXCLUDED.notes, tenant_leads.notes),
        added_by_user_id = COALESCE(EXCLUDED.added_by_user_id, tenant_leads.added_by_user_id)
RETURNING tenant_id, person_id, status, notes, added_at, added_by_user_id
`

type AddTenantLeadParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	PersonID      pgtype.UUID `json:"person_id"`
	Notes         pgtype.Text `json:"notes"`
	AddedByUserID pgtype.UUID `json:"added_by_user_id"`
	Status        pgtype.Text `json:"status"`
}

// tenant_leads — per-tenant association with canonical persons.
func (q *Queries) AddTenantLead(ctx context.Context, arg AddTenantLeadParams) (TenantLead, error) {
	row := q.db.QueryRow(ctx, addTenantLead,
		arg.TenantID,
		arg.PersonID,
		arg.Notes,
		arg.AddedByUserID,
		arg.Status,
	)
	var i TenantLead
	err := row.Scan(
		&i.TenantID,
		&i.PersonID,
		&i.Status,
		&i.Notes,
		&i.AddedAt,
		&i.AddedByUserID,
	)
	return i, err
}

const countTenantLeads = `-- name: CountTenantLeads :one
SELECT COUNT(*) FROM tenant_leads
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2::text)
`

type CountTenantLeadsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
}

func (q *Queries) CountTenantLeads(ctx context.Context, arg CountTenantLeadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantLeads, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTenantLead = `-- name: GetTenantLead :one
SELECT tenant_id, person_id, status, notes, added_at, added_by_user_id FROM tenant_leads
WHERE tenant_id = $1 AND person_id = $2
`

type GetTenantLeadParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PersonID pgtype.UUID `json:"person_id"`
}

func (q *Queries) GetTenantLead(ctx context.Context, arg GetTenantLeadParams) (TenantLead, error) {
	row := q.db.QueryRow(ctx, getTenantLead, arg.TenantID, arg.PersonID)
	var i TenantLead
	err := row.Scan(
		&i.TenantID,
		&i.PersonID,
		&i.Status,
		&i.Notes,
		&i.AddedAt,
		&i.AddedByUserID,
	)
	return i, err
}

const listTenantLeads = `-- name: ListTenantLeads :many
SELECT tl.tenant_id, tl.person_id, tl.status, tl.notes, tl.added_at, tl.added_by_user_id,
       p.canonical_name, p.first_name, p.last_name
FROM tenant_leads tl
JOIN persons p ON p.id = tl.person_id
WHERE tl.tenant_id = $1
  AND ($4::text IS NULL OR tl.status = $4::text)
ORDER BY tl.added_at DESC
LIMIT $2 OFFSET $3
`

type ListTenantLeadsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   pgtype.Text `json:"status"`
}

type ListTenantLeadsRow struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	PersonID      pgtype.UUID        `json:"person_id"`
	Status        string             `json:"status"`
	Notes         pgtype.Text        `json:"notes"`
	AddedAt       pgtype.Timestamptz `json:"added_at"`
	AddedByUserID pgtype.UUID        `json:"added_by_user_id"`
	CanonicalName string             `json:"canonical_name"`
	FirstName     pgtype.Text        `json:"first_name"`
	LastName      pgtype.Text        `json:"last_name"`
}

// ListTenantLeads returns this tenant's saved leads with the canonical
// person attached, newest-first. Filter by status with `sqlc.narg`:
// pass NULL to list all statuses.
func (q *Queries) ListTenantLeads(ctx context.Context, arg ListTenantLeadsParams) ([]ListTenantLeadsRow, error) {
	rows, err := q.db.Query(ctx, listTenantLeads,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantLeadsRow{}
	for rows.Next() {
		var i ListTenantLeadsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.PersonID,
			&i.Status,
			&i.Notes,
			&i.AddedAt,
			&i.AddedByUserID,
			&i.CanonicalName,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTenantLead = `-- name: RemoveTenantLead :exec
DELETE FROM tenant_leads WHERE tenant_id = $1 AND person_id = $2
`

type RemoveTenantLeadParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PersonID pgtype.UUID `json:"person_id"`
}

func (q *Queries) RemoveTenantLead(ctx context.Context, arg RemoveTenantLeadParams) error {
	_, err := q.db.Exec(ctx, removeTenantLead, arg.TenantID, arg.PersonID)
	return err
}

const updateTenantLeadNotes = `-- name: UpdateTenantLeadNotes :exec
UPDATE tenant_leads SET notes = $3
WHERE tenant_id = $1 AND person_id = $2
`

type UpdateTenantLeadNotesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PersonID pgtype.UUID `json:"person_id"`
	Notes    pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateTenantLeadNotes(ctx context.Context, arg UpdateTenantLeadNotesParams) error {
	_, err := q.db.Exec(ctx, updateTenantLeadNotes, arg.TenantID, arg.PersonID, arg.Notes)
	return err
}

const updateTenantLeadStatus = `-- name: UpdateTenantLeadStatus :exec
UPDATE tenant_leads SET status = $3
WHERE tenant_id = $1 AND person_id = $2
`

type UpdateTenantLeadStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PersonID pgtype.UUID `json:"person_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateTenantLeadStatus(ctx context.Context, arg UpdateTenantLeadStatusParams) error {
	_, err := q.db.Exec(ctx, updateTenantLeadStatus, arg.TenantID, arg.PersonID, arg.Status)
	return err
}
