// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: verification.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (email, person_id, verification_method)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE
    SET person_id = COALESCE(emails.person_id, EXCLUDED.person_id)
RETURNING id, email, person_id, verified_at, verification_method, bounce_count, is_catchall, created_at
`

type CreateEmailParams struct {
	Email              string      `json:"email"`
	PersonID           pgtype.UUID `json:"person_id"`
	VerificationMethod pgtype.Text `json:"verification_method"`
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, createEmail, arg.Email, arg.PersonID, arg.VerificationMethod)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PersonID,
		&i.VerifiedAt,
		&i.VerificationMethod,
		&i.BounceCount,
		&i.IsCatchall,
		&i.CreatedAt,
	)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, domain, mx_records, is_catchall, last_verified_at FROM domains WHERE domain = $1
`

func (q *Queries) GetDomainByName(ctx context.Context, domain string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByName, domain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.MxRecords,
		&i.IsCatchall,
		&i.LastVerifiedAt,
	)
	return i, err
}

const listUnverifiedEmails = `-- name: ListUnverifiedEmails :many
SELECT id, email, person_id, verified_at, verification_method, bounce_count, is_catchall, created_at FROM emails
WHERE verified_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListUnverifiedEmails(ctx context.Context, limit int32) ([]Email, error) {
	rows, err := q.db.Query(ctx, listUnverifiedEmails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Email{}
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PersonID,
			&i.VerifiedAt,
			&i.VerificationMethod,
			&i.BounceCount,
			&i.IsCatchall,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDomainCatchall = `-- name: UpdateDomainCatchall :exec
UPDATE domains SET
    is_catchall = $2,
    last_verified_at = NOW()
WHERE domain = $1
`

type UpdateDomainCatchallParams struct {
	Domain     string      `json:"domain"`
	IsCatchall pgtype.Bool `json:"is_catchall"`
}

func (q *Queries) UpdateDomainCatchall(ctx context.Context, arg UpdateDomainCatchallParams) error {
	_, err := q.db.Exec(ctx, updateDomainCatchall, arg.Domain, arg.IsCatchall)
	return err
}

const updateEmailVerification = `-- name: UpdateEmailVerification :exec
UPDATE emails SET
    verified_at = NOW(),
    verification_method = $2,
    bounce_count = $3,
    is_catchall = $4
WHERE id = $1
`

type UpdateEmailVerificationParams struct {
	ID                 pgtype.UUID `json:"id"`
	VerificationMethod pgtype.Text `json:"verification_method"`
	BounceCount        pgtype.Int4 `json:"bounce_count"`
	IsCatchall         pgtype.Bool `json:"is_catchall"`
}

func (q *Queries) UpdateEmailVerification(ctx context.Context, arg UpdateEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, updateEmailVerification,
		arg.ID,
		arg.VerificationMethod,
		arg.BounceCount,
		arg.IsCatchall,
	)
	return err
}

const upsertDomain = `-- name: UpsertDomain :one
INSERT INTO domains (domain, mx_records, is_catchall, last_verified_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (domain) DO UPDATE
    SET mx_records      = EXCLUDED.mx_records,
        -- Preserve a previously-established catch-all flag if the new
        -- probe didn't run (NULL means "unknown").
        is_catchall      = COALESCE(EXCLUDED.is_catchall, domains.is_catchall),
        last_verified_at = NOW()
RETURNING id, domain, mx_records, is_catchall, last_verified_at
`

type UpsertDomainParams struct {
	Domain     string      `json:"domain"`
	MxRecords  []string    `json:"mx_records"`
	IsCatchall pgtype.Bool `json:"is_catchall"`
}

func (q *Queries) UpsertDomain(ctx context.Context, arg UpsertDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, upsertDomain, arg.Domain, arg.MxRecords, arg.IsCatchall)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.MxRecords,
		&i.IsCatchall,
		&i.LastVerifiedAt,
	)
	return i, err
}
